AcceleratorConfig:
  Board: pynq-z2
  Driver: python
  Interface: axi_stream
  Precision:
    Input: float
    Output: float
Backend: VivadoAccelerator
ClockPeriod: 5
ClockUncertainty: 12.5%
HLSConfig:
  Model:
    BramFactor: 1000000000
    Precision:
      default: ap_fixed<16,6>
    ReuseFactor: 4000000000000
    Strategy: Resource
    TraceOutput: false
IOType: io_stream
InputData: null
KerasModel: !keras_model 'pynqz2m2/hls4ml_prj_pynq/keras_model.keras'
OutputDir: pynqz2m2/hls4ml_prj_pynq
OutputPredictions: null
Part: xc7z020clg400-1
ProjectName: myproject
Stamp: 97552dc7
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
