// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_HH_
#define _compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0.h"
#include "shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s.h"

namespace ap_rtl {

struct compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s : public sc_module {
    // Port declarations 34
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<16> > in_elem_data_0_V_read;
    sc_in< sc_lv<16> > in_elem_data_1_V_read;
    sc_in< sc_lv<16> > in_elem_data_2_V_read;
    sc_in< sc_lv<16> > in_elem_data_3_V_read;
    sc_out< sc_lv<16> > res_stream_V_data_0_V_din;
    sc_in< sc_logic > res_stream_V_data_0_V_full_n;
    sc_out< sc_logic > res_stream_V_data_0_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_1_V_din;
    sc_in< sc_logic > res_stream_V_data_1_V_full_n;
    sc_out< sc_logic > res_stream_V_data_1_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_2_V_din;
    sc_in< sc_logic > res_stream_V_data_2_V_full_n;
    sc_out< sc_logic > res_stream_V_data_2_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_3_V_din;
    sc_in< sc_logic > res_stream_V_data_3_V_full_n;
    sc_out< sc_logic > res_stream_V_data_3_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_4_V_din;
    sc_in< sc_logic > res_stream_V_data_4_V_full_n;
    sc_out< sc_logic > res_stream_V_data_4_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_5_V_din;
    sc_in< sc_logic > res_stream_V_data_5_V_full_n;
    sc_out< sc_logic > res_stream_V_data_5_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_6_V_din;
    sc_in< sc_logic > res_stream_V_data_6_V_full_n;
    sc_out< sc_logic > res_stream_V_data_6_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_7_V_din;
    sc_in< sc_logic > res_stream_V_data_7_V_full_n;
    sc_out< sc_logic > res_stream_V_data_7_V_write;


    // Module declarations
    compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s(sc_module_name name);
    SC_HAS_PROCESS(compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s);

    ~compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s();

    sc_trace_file* mVcdFile;

    dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0* grp_dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0_fu_217;
    shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s* call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<16> > kernel_data_V_3_4;
    sc_signal< sc_lv<16> > kernel_data_V_3_5;
    sc_signal< sc_lv<16> > kernel_data_V_3_6;
    sc_signal< sc_lv<16> > kernel_data_V_3_7;
    sc_signal< sc_lv<16> > kernel_data_V_3_8;
    sc_signal< sc_lv<16> > kernel_data_V_3_9;
    sc_signal< sc_lv<16> > kernel_data_V_3_10;
    sc_signal< sc_lv<16> > kernel_data_V_3_11;
    sc_signal< sc_lv<16> > kernel_data_V_3_16;
    sc_signal< sc_lv<16> > kernel_data_V_3_17;
    sc_signal< sc_lv<16> > kernel_data_V_3_18;
    sc_signal< sc_lv<16> > kernel_data_V_3_19;
    sc_signal< sc_lv<16> > kernel_data_V_3_20;
    sc_signal< sc_lv<16> > kernel_data_V_3_21;
    sc_signal< sc_lv<16> > kernel_data_V_3_22;
    sc_signal< sc_lv<16> > kernel_data_V_3_23;
    sc_signal< sc_lv<16> > kernel_data_V_3_28;
    sc_signal< sc_lv<16> > kernel_data_V_3_29;
    sc_signal< sc_lv<16> > kernel_data_V_3_30;
    sc_signal< sc_lv<16> > kernel_data_V_3_31;
    sc_signal< sc_lv<16> > kernel_data_V_3_32;
    sc_signal< sc_lv<16> > kernel_data_V_3_33;
    sc_signal< sc_lv<16> > kernel_data_V_3_34;
    sc_signal< sc_lv<16> > kernel_data_V_3_35;
    sc_signal< sc_lv<16> > kernel_data_V_3_0;
    sc_signal< sc_lv<16> > kernel_data_V_3_1;
    sc_signal< sc_lv<16> > kernel_data_V_3_2;
    sc_signal< sc_lv<16> > kernel_data_V_3_3;
    sc_signal< sc_lv<16> > kernel_data_V_3_12;
    sc_signal< sc_lv<16> > kernel_data_V_3_13;
    sc_signal< sc_lv<16> > kernel_data_V_3_14;
    sc_signal< sc_lv<16> > kernel_data_V_3_15;
    sc_signal< sc_lv<16> > kernel_data_V_3_24;
    sc_signal< sc_lv<16> > kernel_data_V_3_25;
    sc_signal< sc_lv<16> > kernel_data_V_3_26;
    sc_signal< sc_lv<16> > kernel_data_V_3_27;
    sc_signal< sc_lv<32> > sX_6;
    sc_signal< sc_lv<32> > sY_6;
    sc_signal< sc_lv<32> > pY_6;
    sc_signal< sc_lv<32> > pX_6;
    sc_signal< sc_logic > res_stream_V_data_0_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > and_ln284_2_reg_1064;
    sc_signal< sc_logic > res_stream_V_data_1_V_blk_n;
    sc_signal< sc_logic > res_stream_V_data_2_V_blk_n;
    sc_signal< sc_logic > res_stream_V_data_3_V_blk_n;
    sc_signal< sc_logic > res_stream_V_data_4_V_blk_n;
    sc_signal< sc_logic > res_stream_V_data_5_V_blk_n;
    sc_signal< sc_logic > res_stream_V_data_6_V_blk_n;
    sc_signal< sc_logic > res_stream_V_data_7_V_blk_n;
    sc_signal< sc_lv<32> > sX_6_load_reg_1032;
    sc_signal< sc_lv<1> > icmp_ln284_fu_833_p2;
    sc_signal< sc_lv<1> > icmp_ln284_reg_1037;
    sc_signal< sc_lv<32> > sY_6_load_reg_1042;
    sc_signal< sc_lv<1> > icmp_ln284_1_fu_843_p2;
    sc_signal< sc_lv<1> > icmp_ln284_1_reg_1047;
    sc_signal< sc_lv<32> > pY_6_load_reg_1052;
    sc_signal< sc_lv<32> > pX_6_load_reg_1058;
    sc_signal< sc_lv<1> > and_ln284_2_fu_901_p2;
    sc_signal< sc_lv<1> > icmp_ln303_fu_947_p2;
    sc_signal< sc_lv<1> > icmp_ln303_reg_1068;
    sc_signal< sc_logic > io_acc_block_signal_op137;
    sc_signal< bool > ap_block_state2;
    sc_signal< sc_logic > grp_dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0_fu_217_ap_ready;
    sc_signal< sc_logic > grp_dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0_fu_217_ap_done;
    sc_signal< bool > ap_block_state2_on_subcall_done;
    sc_signal< sc_lv<32> > select_ln318_fu_968_p3;
    sc_signal< sc_lv<32> > select_ln318_reg_1072;
    sc_signal< sc_lv<1> > icmp_ln307_fu_987_p2;
    sc_signal< sc_lv<1> > icmp_ln307_reg_1077;
    sc_signal< sc_lv<32> > select_ln313_fu_1008_p3;
    sc_signal< sc_lv<32> > select_ln313_reg_1081;
    sc_signal< sc_logic > grp_dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0_fu_217_ap_start;
    sc_signal< sc_logic > grp_dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0_fu_217_ap_idle;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0_fu_217_ap_return_0;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0_fu_217_ap_return_1;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0_fu_217_ap_return_2;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0_fu_217_ap_return_3;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0_fu_217_ap_return_4;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0_fu_217_ap_return_5;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0_fu_217_ap_return_6;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0_fu_217_ap_return_7;
    sc_signal< sc_logic > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_start;
    sc_signal< sc_logic > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_done;
    sc_signal< sc_logic > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_idle;
    sc_signal< sc_logic > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_ready;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_0;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_1;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_2;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_3;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_4;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_5;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_6;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_7;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_8;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_9;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_10;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_11;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_12;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_13;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_14;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_15;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_16;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_17;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_18;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_19;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_20;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_21;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_22;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_23;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_24;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_25;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_26;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_27;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_28;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_29;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_30;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_31;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_32;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_33;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_34;
    sc_signal< sc_lv<16> > call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_return_35;
    sc_signal< sc_lv<32> > ap_phi_mux_storemerge_phi_fu_210_p4;
    sc_signal< sc_lv<32> > storemerge_reg_206;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > grp_dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0_fu_217_ap_start_reg;
    sc_signal< sc_lv<32> > add_ln311_fu_992_p2;
    sc_signal< sc_lv<32> > add_ln316_fu_952_p2;
    sc_signal< sc_lv<31> > tmp_3_fu_853_p4;
    sc_signal< sc_lv<31> > tmp_4_fu_873_p4;
    sc_signal< sc_lv<1> > icmp_ln284_2_fu_863_p2;
    sc_signal< sc_lv<1> > icmp_ln284_3_fu_883_p2;
    sc_signal< sc_lv<1> > and_ln284_1_fu_895_p2;
    sc_signal< sc_lv<1> > and_ln284_fu_889_p2;
    sc_signal< sc_lv<32> > add_ln318_fu_963_p2;
    sc_signal< sc_lv<32> > add_ln313_fu_1003_p2;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< bool > ap_condition_147;
    sc_signal< bool > ap_condition_156;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_state2;
    static const sc_lv<3> ap_ST_fsm_state3;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<31> ap_const_lv31_0;
    static const sc_lv<32> ap_const_lv32_11;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln311_fu_992_p2();
    void thread_add_ln313_fu_1003_p2();
    void thread_add_ln316_fu_952_p2();
    void thread_add_ln318_fu_963_p2();
    void thread_and_ln284_1_fu_895_p2();
    void thread_and_ln284_2_fu_901_p2();
    void thread_and_ln284_fu_889_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_block_state2();
    void thread_ap_block_state2_on_subcall_done();
    void thread_ap_condition_147();
    void thread_ap_condition_156();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_storemerge_phi_fu_210_p4();
    void thread_ap_ready();
    void thread_call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config5_s_fu_297_ap_start();
    void thread_grp_dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0_fu_217_ap_start();
    void thread_icmp_ln284_1_fu_843_p2();
    void thread_icmp_ln284_2_fu_863_p2();
    void thread_icmp_ln284_3_fu_883_p2();
    void thread_icmp_ln284_fu_833_p2();
    void thread_icmp_ln303_fu_947_p2();
    void thread_icmp_ln307_fu_987_p2();
    void thread_io_acc_block_signal_op137();
    void thread_res_stream_V_data_0_V_blk_n();
    void thread_res_stream_V_data_0_V_din();
    void thread_res_stream_V_data_0_V_write();
    void thread_res_stream_V_data_1_V_blk_n();
    void thread_res_stream_V_data_1_V_din();
    void thread_res_stream_V_data_1_V_write();
    void thread_res_stream_V_data_2_V_blk_n();
    void thread_res_stream_V_data_2_V_din();
    void thread_res_stream_V_data_2_V_write();
    void thread_res_stream_V_data_3_V_blk_n();
    void thread_res_stream_V_data_3_V_din();
    void thread_res_stream_V_data_3_V_write();
    void thread_res_stream_V_data_4_V_blk_n();
    void thread_res_stream_V_data_4_V_din();
    void thread_res_stream_V_data_4_V_write();
    void thread_res_stream_V_data_5_V_blk_n();
    void thread_res_stream_V_data_5_V_din();
    void thread_res_stream_V_data_5_V_write();
    void thread_res_stream_V_data_6_V_blk_n();
    void thread_res_stream_V_data_6_V_din();
    void thread_res_stream_V_data_6_V_write();
    void thread_res_stream_V_data_7_V_blk_n();
    void thread_res_stream_V_data_7_V_din();
    void thread_res_stream_V_data_7_V_write();
    void thread_select_ln313_fu_1008_p3();
    void thread_select_ln318_fu_968_p3();
    void thread_tmp_3_fu_853_p4();
    void thread_tmp_4_fu_873_p4();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
