-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity compute_output_buffer_2d_array_array_ap_fixed_4_2_5_3_0_4u_config19_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_elem_data_0_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
    in_elem_data_1_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
    in_elem_data_2_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
    in_elem_data_3_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
    in_elem_data_4_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
    in_elem_data_5_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
    in_elem_data_6_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
    in_elem_data_7_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
    res_stream_V_data_0_V_din : OUT STD_LOGIC_VECTOR (3 downto 0);
    res_stream_V_data_0_V_full_n : IN STD_LOGIC;
    res_stream_V_data_0_V_write : OUT STD_LOGIC;
    res_stream_V_data_1_V_din : OUT STD_LOGIC_VECTOR (3 downto 0);
    res_stream_V_data_1_V_full_n : IN STD_LOGIC;
    res_stream_V_data_1_V_write : OUT STD_LOGIC;
    res_stream_V_data_2_V_din : OUT STD_LOGIC_VECTOR (3 downto 0);
    res_stream_V_data_2_V_full_n : IN STD_LOGIC;
    res_stream_V_data_2_V_write : OUT STD_LOGIC;
    res_stream_V_data_3_V_din : OUT STD_LOGIC_VECTOR (3 downto 0);
    res_stream_V_data_3_V_full_n : IN STD_LOGIC;
    res_stream_V_data_3_V_write : OUT STD_LOGIC );
end;


architecture behav of compute_output_buffer_2d_array_array_ap_fixed_4_2_5_3_0_4u_config19_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal kernel_data_V_6_8 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_9 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_10 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_11 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_12 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_13 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_14 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_15 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_16 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_17 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_18 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_19 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_20 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_21 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_22 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_23 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_32 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_33 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_34 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_35 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_36 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_37 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_38 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_39 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_40 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_41 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_42 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_43 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_44 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_45 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_46 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_47 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_57 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_58 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_59 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_60 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_62 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_63 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_64 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_65 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_66 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_67 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_68 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_70 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_6_71 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal sX_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sY_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pY_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pX_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal res_stream_V_data_0_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal and_ln284_2_reg_1750 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_stream_V_data_1_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_2_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_3_V_blk_n : STD_LOGIC;
    signal newret2_reg_1378 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret4_reg_1383 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret6_reg_1388 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret8_reg_1393 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret10_reg_1398 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret12_reg_1403 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret14_reg_1408 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret16_reg_1413 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret18_reg_1418 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret20_reg_1423 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret22_reg_1428 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret24_reg_1433 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret26_reg_1438 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret28_reg_1443 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret30_reg_1448 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret32_reg_1453 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret34_reg_1458 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret36_reg_1463 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret38_reg_1468 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret40_reg_1473 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret42_reg_1478 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret44_reg_1483 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret46_reg_1488 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret48_reg_1493 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret50_reg_1498 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret52_reg_1503 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret54_reg_1508 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret56_reg_1513 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret58_reg_1518 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret62_reg_1523 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret64_reg_1528 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret66_reg_1533 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret68_reg_1538 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret70_reg_1543 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret72_reg_1548 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret74_reg_1553 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret76_reg_1558 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret78_reg_1563 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret80_reg_1568 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret82_reg_1573 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret84_reg_1578 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret86_reg_1583 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret88_reg_1588 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret90_reg_1593 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret92_reg_1598 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret94_reg_1603 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret96_reg_1608 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret98_reg_1613 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret100_reg_1618 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret102_reg_1623 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret104_reg_1628 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret106_reg_1633 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret108_reg_1638 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret110_reg_1643 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret112_reg_1648 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret114_reg_1653 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret116_reg_1658 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret118_reg_1663 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret120_reg_1668 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret122_reg_1673 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret124_reg_1678 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret126_reg_1683 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret128_reg_1688 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret130_reg_1693 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret132_reg_1698 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret134_reg_1703 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret136_reg_1708 : STD_LOGIC_VECTOR (3 downto 0);
    signal newret138_reg_1713 : STD_LOGIC_VECTOR (3 downto 0);
    signal sX_3_load_reg_1718 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln284_fu_1203_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln284_reg_1723 : STD_LOGIC_VECTOR (0 downto 0);
    signal sY_3_load_reg_1728 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln284_1_fu_1213_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln284_1_reg_1733 : STD_LOGIC_VECTOR (0 downto 0);
    signal pY_3_load_reg_1738 : STD_LOGIC_VECTOR (31 downto 0);
    signal pX_3_load_reg_1744 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln284_2_fu_1271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_out_0_V_reg_1754 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_ready : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_done : STD_LOGIC;
    signal res_out_1_V_reg_1759 : STD_LOGIC_VECTOR (3 downto 0);
    signal res_out_2_V_reg_1764 : STD_LOGIC_VECTOR (3 downto 0);
    signal res_out_3_V_reg_1769 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln303_fu_1293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln303_reg_1774 : STD_LOGIC_VECTOR (0 downto 0);
    signal io_acc_block_signal_op198 : STD_LOGIC;
    signal ap_block_state4 : BOOLEAN;
    signal select_ln318_fu_1314_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln318_reg_1778 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln307_fu_1333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln307_reg_1783 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln313_fu_1354_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln313_reg_1787 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_start : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_idle : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_return_0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_return_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_return_2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_return_3 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_start : STD_LOGIC;
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_done : STD_LOGIC;
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_idle : STD_LOGIC;
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_ready : STD_LOGIC;
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_0 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_2 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_3 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_4 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_5 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_6 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_7 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_8 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_9 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_10 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_11 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_12 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_13 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_14 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_15 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_16 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_17 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_18 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_19 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_20 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_21 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_22 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_23 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_24 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_25 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_26 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_27 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_28 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_29 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_30 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_31 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_32 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_33 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_34 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_35 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_36 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_37 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_38 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_39 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_40 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_41 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_42 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_43 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_44 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_45 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_46 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_47 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_48 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_49 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_50 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_51 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_52 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_53 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_54 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_55 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_56 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_57 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_58 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_59 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_60 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_61 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_62 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_63 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_64 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_65 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_66 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_67 : STD_LOGIC_VECTOR (3 downto 0);
    signal call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_68 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_phi_mux_storemerge_phi_fu_252_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal storemerge_reg_248 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln311_fu_1338_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln316_fu_1298_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_1223_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_4_fu_1243_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln284_10_fu_1233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln284_11_fu_1253_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln284_1_fu_1265_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln284_fu_1259_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln318_fu_1309_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln313_fu_1349_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_condition_289 : BOOLEAN;
    signal ap_condition_298 : BOOLEAN;

    component dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_0_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_1_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_2_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_3_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_4_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_5_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_6_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_7_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_8_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_9_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_10_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_11_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_12_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_13_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_14_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_16_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_17_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_18_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_19_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_20_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_21_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_22_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_23_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_24_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_25_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_26_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_27_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_28_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_29_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_30_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_31_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_32_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_33_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_34_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_35_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_36_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_37_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_38_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_39_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_40_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_41_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_42_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_43_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_44_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_45_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_46_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_47_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_49_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_50_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_51_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_52_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_54_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_55_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_56_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_57_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_58_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_59_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_60_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_62_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_63_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_64_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_65_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_66_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_67_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_68_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_69_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_70_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        data_71_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_elem_data_0_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        in_elem_data_1_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        in_elem_data_2_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        in_elem_data_3_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        in_elem_data_4_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        in_elem_data_5_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        in_elem_data_6_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        in_elem_data_7_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_8_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_9_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_10_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_11_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_12_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_13_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_14_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_15_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_16_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_17_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_18_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_19_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_20_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_21_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_22_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_23_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_32_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_33_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_34_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_35_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_36_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_37_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_38_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_39_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_40_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_41_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_42_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_43_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_44_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_45_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_46_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_47_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_57_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_58_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_59_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_60_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_62_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_63_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_64_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_65_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_66_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_67_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_68_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_70_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_window_71_V_read : IN STD_LOGIC_VECTOR (3 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_16 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_17 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_18 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_19 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_20 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_21 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_22 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_23 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_24 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_25 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_26 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_27 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_28 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_29 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_30 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_31 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_32 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_33 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_34 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_35 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_36 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_37 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_38 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_39 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_40 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_41 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_42 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_43 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_44 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_45 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_46 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_47 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_48 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_49 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_50 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_51 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_52 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_53 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_54 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_55 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_56 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_57 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_58 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_59 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_60 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_61 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_62 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_63 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_64 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_65 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_66 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_67 : OUT STD_LOGIC_VECTOR (3 downto 0);
        ap_return_68 : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;



begin
    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259 : component dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_start,
        ap_done => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_done,
        ap_idle => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_idle,
        ap_ready => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_ready,
        data_0_V_read => newret2_reg_1378,
        data_1_V_read => newret4_reg_1383,
        data_2_V_read => newret6_reg_1388,
        data_3_V_read => newret8_reg_1393,
        data_4_V_read => newret10_reg_1398,
        data_5_V_read => newret12_reg_1403,
        data_6_V_read => newret14_reg_1408,
        data_7_V_read => newret16_reg_1413,
        data_8_V_read => newret46_reg_1488,
        data_9_V_read => newret48_reg_1493,
        data_10_V_read => newret50_reg_1498,
        data_11_V_read => newret52_reg_1503,
        data_12_V_read => newret54_reg_1508,
        data_13_V_read => newret56_reg_1513,
        data_14_V_read => newret58_reg_1518,
        data_16_V_read => newret62_reg_1523,
        data_17_V_read => newret64_reg_1528,
        data_18_V_read => newret66_reg_1533,
        data_19_V_read => newret68_reg_1538,
        data_20_V_read => newret70_reg_1543,
        data_21_V_read => newret72_reg_1548,
        data_22_V_read => newret74_reg_1553,
        data_23_V_read => newret76_reg_1558,
        data_24_V_read => newret18_reg_1418,
        data_25_V_read => newret20_reg_1423,
        data_26_V_read => newret22_reg_1428,
        data_27_V_read => newret24_reg_1433,
        data_28_V_read => newret26_reg_1438,
        data_29_V_read => newret28_reg_1443,
        data_30_V_read => newret30_reg_1448,
        data_31_V_read => newret32_reg_1453,
        data_32_V_read => newret78_reg_1563,
        data_33_V_read => newret80_reg_1568,
        data_34_V_read => newret82_reg_1573,
        data_35_V_read => newret84_reg_1578,
        data_36_V_read => newret86_reg_1583,
        data_37_V_read => newret88_reg_1588,
        data_38_V_read => newret90_reg_1593,
        data_39_V_read => newret92_reg_1598,
        data_40_V_read => newret94_reg_1603,
        data_41_V_read => newret96_reg_1608,
        data_42_V_read => newret98_reg_1613,
        data_43_V_read => newret100_reg_1618,
        data_44_V_read => newret102_reg_1623,
        data_45_V_read => newret104_reg_1628,
        data_46_V_read => newret106_reg_1633,
        data_47_V_read => newret108_reg_1638,
        data_49_V_read => newret34_reg_1458,
        data_50_V_read => newret36_reg_1463,
        data_51_V_read => newret38_reg_1468,
        data_52_V_read => newret40_reg_1473,
        data_54_V_read => newret42_reg_1478,
        data_55_V_read => newret44_reg_1483,
        data_56_V_read => newret110_reg_1643,
        data_57_V_read => newret112_reg_1648,
        data_58_V_read => newret114_reg_1653,
        data_59_V_read => newret116_reg_1658,
        data_60_V_read => newret118_reg_1663,
        data_62_V_read => newret120_reg_1668,
        data_63_V_read => newret122_reg_1673,
        data_64_V_read => newret124_reg_1678,
        data_65_V_read => newret126_reg_1683,
        data_66_V_read => newret128_reg_1688,
        data_67_V_read => newret130_reg_1693,
        data_68_V_read => newret132_reg_1698,
        data_69_V_read => newret134_reg_1703,
        data_70_V_read => newret136_reg_1708,
        data_71_V_read => newret138_reg_1713,
        ap_return_0 => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_return_0,
        ap_return_1 => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_return_1,
        ap_return_2 => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_return_2,
        ap_return_3 => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_return_3);

    call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331 : component shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_start,
        ap_done => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_done,
        ap_idle => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_idle,
        ap_ready => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_ready,
        in_elem_data_0_V_read => in_elem_data_0_V_read,
        in_elem_data_1_V_read => in_elem_data_1_V_read,
        in_elem_data_2_V_read => in_elem_data_2_V_read,
        in_elem_data_3_V_read => in_elem_data_3_V_read,
        in_elem_data_4_V_read => in_elem_data_4_V_read,
        in_elem_data_5_V_read => in_elem_data_5_V_read,
        in_elem_data_6_V_read => in_elem_data_6_V_read,
        in_elem_data_7_V_read => in_elem_data_7_V_read,
        kernel_window_8_V_read => kernel_data_V_6_8,
        kernel_window_9_V_read => kernel_data_V_6_9,
        kernel_window_10_V_read => kernel_data_V_6_10,
        kernel_window_11_V_read => kernel_data_V_6_11,
        kernel_window_12_V_read => kernel_data_V_6_12,
        kernel_window_13_V_read => kernel_data_V_6_13,
        kernel_window_14_V_read => kernel_data_V_6_14,
        kernel_window_15_V_read => kernel_data_V_6_15,
        kernel_window_16_V_read => kernel_data_V_6_16,
        kernel_window_17_V_read => kernel_data_V_6_17,
        kernel_window_18_V_read => kernel_data_V_6_18,
        kernel_window_19_V_read => kernel_data_V_6_19,
        kernel_window_20_V_read => kernel_data_V_6_20,
        kernel_window_21_V_read => kernel_data_V_6_21,
        kernel_window_22_V_read => kernel_data_V_6_22,
        kernel_window_23_V_read => kernel_data_V_6_23,
        kernel_window_32_V_read => kernel_data_V_6_32,
        kernel_window_33_V_read => kernel_data_V_6_33,
        kernel_window_34_V_read => kernel_data_V_6_34,
        kernel_window_35_V_read => kernel_data_V_6_35,
        kernel_window_36_V_read => kernel_data_V_6_36,
        kernel_window_37_V_read => kernel_data_V_6_37,
        kernel_window_38_V_read => kernel_data_V_6_38,
        kernel_window_39_V_read => kernel_data_V_6_39,
        kernel_window_40_V_read => kernel_data_V_6_40,
        kernel_window_41_V_read => kernel_data_V_6_41,
        kernel_window_42_V_read => kernel_data_V_6_42,
        kernel_window_43_V_read => kernel_data_V_6_43,
        kernel_window_44_V_read => kernel_data_V_6_44,
        kernel_window_45_V_read => kernel_data_V_6_45,
        kernel_window_46_V_read => kernel_data_V_6_46,
        kernel_window_47_V_read => kernel_data_V_6_47,
        kernel_window_57_V_read => kernel_data_V_6_57,
        kernel_window_58_V_read => kernel_data_V_6_58,
        kernel_window_59_V_read => kernel_data_V_6_59,
        kernel_window_60_V_read => kernel_data_V_6_60,
        kernel_window_62_V_read => kernel_data_V_6_62,
        kernel_window_63_V_read => kernel_data_V_6_63,
        kernel_window_64_V_read => kernel_data_V_6_64,
        kernel_window_65_V_read => kernel_data_V_6_65,
        kernel_window_66_V_read => kernel_data_V_6_66,
        kernel_window_67_V_read => kernel_data_V_6_67,
        kernel_window_68_V_read => kernel_data_V_6_68,
        kernel_window_70_V_read => kernel_data_V_6_70,
        kernel_window_71_V_read => kernel_data_V_6_71,
        ap_return_0 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_0,
        ap_return_1 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_1,
        ap_return_2 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_2,
        ap_return_3 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_3,
        ap_return_4 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_4,
        ap_return_5 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_5,
        ap_return_6 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_6,
        ap_return_7 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_7,
        ap_return_8 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_8,
        ap_return_9 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_9,
        ap_return_10 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_10,
        ap_return_11 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_11,
        ap_return_12 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_12,
        ap_return_13 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_13,
        ap_return_14 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_14,
        ap_return_15 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_15,
        ap_return_16 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_16,
        ap_return_17 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_17,
        ap_return_18 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_18,
        ap_return_19 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_19,
        ap_return_20 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_20,
        ap_return_21 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_21,
        ap_return_22 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_22,
        ap_return_23 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_23,
        ap_return_24 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_24,
        ap_return_25 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_25,
        ap_return_26 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_26,
        ap_return_27 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_27,
        ap_return_28 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_28,
        ap_return_29 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_29,
        ap_return_30 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_30,
        ap_return_31 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_31,
        ap_return_32 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_32,
        ap_return_33 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_33,
        ap_return_34 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_34,
        ap_return_35 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_35,
        ap_return_36 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_36,
        ap_return_37 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_37,
        ap_return_38 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_38,
        ap_return_39 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_39,
        ap_return_40 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_40,
        ap_return_41 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_41,
        ap_return_42 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_42,
        ap_return_43 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_43,
        ap_return_44 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_44,
        ap_return_45 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_45,
        ap_return_46 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_46,
        ap_return_47 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_47,
        ap_return_48 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_48,
        ap_return_49 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_49,
        ap_return_50 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_50,
        ap_return_51 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_51,
        ap_return_52 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_52,
        ap_return_53 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_53,
        ap_return_54 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_54,
        ap_return_55 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_55,
        ap_return_56 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_56,
        ap_return_57 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_57,
        ap_return_58 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_58,
        ap_return_59 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_59,
        ap_return_60 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_60,
        ap_return_61 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_61,
        ap_return_62 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_62,
        ap_return_63 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_63,
        ap_return_64 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_64,
        ap_return_65 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_65,
        ap_return_66 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_66,
        ap_return_67 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_67,
        ap_return_68 => call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_68);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_ready = ap_const_logic_1)) then 
                    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    pX_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_289)) then
                if ((icmp_ln303_fu_1293_p2 = ap_const_lv1_1)) then 
                    pX_3 <= ap_const_lv32_0;
                elsif ((icmp_ln303_fu_1293_p2 = ap_const_lv1_0)) then 
                    pX_3 <= add_ln316_fu_1298_p2;
                end if;
            end if; 
        end if;
    end process;

    pY_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_298)) then
                if ((icmp_ln307_fu_1333_p2 = ap_const_lv1_1)) then 
                    pY_3 <= ap_const_lv32_0;
                elsif ((icmp_ln307_fu_1333_p2 = ap_const_lv1_0)) then 
                    pY_3 <= add_ln311_fu_1338_p2;
                end if;
            end if; 
        end if;
    end process;

    sX_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln303_reg_1774 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                sX_3 <= select_ln318_reg_1778;
            elsif ((not(((io_acc_block_signal_op198 = ap_const_logic_0) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln303_fu_1293_p2 = ap_const_lv1_1))) then 
                sX_3 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    storemerge_reg_248_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((io_acc_block_signal_op198 = ap_const_logic_0) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln307_fu_1333_p2 = ap_const_lv1_1) and (icmp_ln303_fu_1293_p2 = ap_const_lv1_1))) then 
                storemerge_reg_248 <= ap_const_lv32_0;
            elsif (((icmp_ln307_reg_1783 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln303_reg_1774 = ap_const_lv1_1))) then 
                storemerge_reg_248 <= select_ln313_reg_1787;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                and_ln284_2_reg_1750 <= and_ln284_2_fu_1271_p2;
                icmp_ln284_1_reg_1733 <= icmp_ln284_1_fu_1213_p2;
                icmp_ln284_reg_1723 <= icmp_ln284_fu_1203_p2;
                kernel_data_V_6_10 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_24;
                kernel_data_V_6_11 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_25;
                kernel_data_V_6_12 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_26;
                kernel_data_V_6_13 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_27;
                kernel_data_V_6_14 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_28;
                kernel_data_V_6_15 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_29;
                kernel_data_V_6_16 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_30;
                kernel_data_V_6_17 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_31;
                kernel_data_V_6_18 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_32;
                kernel_data_V_6_19 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_33;
                kernel_data_V_6_20 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_34;
                kernel_data_V_6_21 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_35;
                kernel_data_V_6_22 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_36;
                kernel_data_V_6_23 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_37;
                kernel_data_V_6_32 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_38;
                kernel_data_V_6_33 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_39;
                kernel_data_V_6_34 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_40;
                kernel_data_V_6_35 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_41;
                kernel_data_V_6_36 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_42;
                kernel_data_V_6_37 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_43;
                kernel_data_V_6_38 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_44;
                kernel_data_V_6_39 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_45;
                kernel_data_V_6_40 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_46;
                kernel_data_V_6_41 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_47;
                kernel_data_V_6_42 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_48;
                kernel_data_V_6_43 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_49;
                kernel_data_V_6_44 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_50;
                kernel_data_V_6_45 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_51;
                kernel_data_V_6_46 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_52;
                kernel_data_V_6_47 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_53;
                kernel_data_V_6_57 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_55;
                kernel_data_V_6_58 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_56;
                kernel_data_V_6_59 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_57;
                kernel_data_V_6_60 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_58;
                kernel_data_V_6_62 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_59;
                kernel_data_V_6_63 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_60;
                kernel_data_V_6_64 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_61;
                kernel_data_V_6_65 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_62;
                kernel_data_V_6_66 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_63;
                kernel_data_V_6_67 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_64;
                kernel_data_V_6_68 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_65;
                kernel_data_V_6_70 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_67;
                kernel_data_V_6_71 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_68;
                kernel_data_V_6_8 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_22;
                kernel_data_V_6_9 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_23;
                newret100_reg_1618 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_49;
                newret102_reg_1623 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_50;
                newret104_reg_1628 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_51;
                newret106_reg_1633 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_52;
                newret108_reg_1638 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_53;
                newret10_reg_1398 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_4;
                newret110_reg_1643 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_54;
                newret112_reg_1648 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_55;
                newret114_reg_1653 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_56;
                newret116_reg_1658 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_57;
                newret118_reg_1663 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_58;
                newret120_reg_1668 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_59;
                newret122_reg_1673 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_60;
                newret124_reg_1678 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_61;
                newret126_reg_1683 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_62;
                newret128_reg_1688 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_63;
                newret12_reg_1403 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_5;
                newret130_reg_1693 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_64;
                newret132_reg_1698 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_65;
                newret134_reg_1703 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_66;
                newret136_reg_1708 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_67;
                newret138_reg_1713 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_68;
                newret14_reg_1408 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_6;
                newret16_reg_1413 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_7;
                newret18_reg_1418 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_8;
                newret20_reg_1423 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_9;
                newret22_reg_1428 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_10;
                newret24_reg_1433 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_11;
                newret26_reg_1438 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_12;
                newret28_reg_1443 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_13;
                newret2_reg_1378 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_0;
                newret30_reg_1448 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_14;
                newret32_reg_1453 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_15;
                newret34_reg_1458 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_16;
                newret36_reg_1463 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_17;
                newret38_reg_1468 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_18;
                newret40_reg_1473 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_19;
                newret42_reg_1478 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_20;
                newret44_reg_1483 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_21;
                newret46_reg_1488 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_22;
                newret48_reg_1493 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_23;
                newret4_reg_1383 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_1;
                newret50_reg_1498 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_24;
                newret52_reg_1503 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_25;
                newret54_reg_1508 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_26;
                newret56_reg_1513 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_27;
                newret58_reg_1518 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_28;
                newret62_reg_1523 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_30;
                newret64_reg_1528 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_31;
                newret66_reg_1533 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_32;
                newret68_reg_1538 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_33;
                newret6_reg_1388 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_2;
                newret70_reg_1543 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_34;
                newret72_reg_1548 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_35;
                newret74_reg_1553 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_36;
                newret76_reg_1558 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_37;
                newret78_reg_1563 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_38;
                newret80_reg_1568 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_39;
                newret82_reg_1573 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_40;
                newret84_reg_1578 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_41;
                newret86_reg_1583 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_42;
                newret88_reg_1588 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_43;
                newret8_reg_1393 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_3;
                newret90_reg_1593 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_44;
                newret92_reg_1598 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_45;
                newret94_reg_1603 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_46;
                newret96_reg_1608 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_47;
                newret98_reg_1613 <= call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_return_48;
                pX_3_load_reg_1744 <= pX_3;
                pY_3_load_reg_1738 <= pY_3;
                sX_3_load_reg_1718 <= sX_3;
                sY_3_load_reg_1728 <= sY_3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((io_acc_block_signal_op198 = ap_const_logic_0) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                icmp_ln303_reg_1774 <= icmp_ln303_fu_1293_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((io_acc_block_signal_op198 = ap_const_logic_0) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln303_fu_1293_p2 = ap_const_lv1_1))) then
                icmp_ln307_reg_1783 <= icmp_ln307_fu_1333_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_out_0_V_reg_1754 <= grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_return_0;
                res_out_1_V_reg_1759 <= grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_return_1;
                res_out_2_V_reg_1764 <= grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_return_2;
                res_out_3_V_reg_1769 <= grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_return_3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln303_reg_1774 = ap_const_lv1_1))) then
                sY_3 <= ap_phi_mux_storemerge_phi_fu_252_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((io_acc_block_signal_op198 = ap_const_logic_0) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) and (icmp_ln307_fu_1333_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln303_fu_1293_p2 = ap_const_lv1_1))) then
                select_ln313_reg_1787 <= select_ln313_fu_1354_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((io_acc_block_signal_op198 = ap_const_logic_0) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) and (icmp_ln303_fu_1293_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                select_ln318_reg_1778 <= select_ln318_fu_1314_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, and_ln284_2_reg_1750, and_ln284_2_fu_1271_p2, ap_CS_fsm_state3, grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_done, io_acc_block_signal_op198)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_lv1_0 = and_ln284_2_fu_1271_p2) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (ap_const_lv1_1 = and_ln284_2_fu_1271_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if ((not(((io_acc_block_signal_op198 = ap_const_logic_0) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln311_fu_1338_p2 <= std_logic_vector(unsigned(pY_3_load_reg_1738) + unsigned(ap_const_lv32_1));
    add_ln313_fu_1349_p2 <= std_logic_vector(unsigned(sY_3_load_reg_1728) + unsigned(ap_const_lv32_1));
    add_ln316_fu_1298_p2 <= std_logic_vector(unsigned(pX_3_load_reg_1744) + unsigned(ap_const_lv32_1));
    add_ln318_fu_1309_p2 <= std_logic_vector(unsigned(sX_3_load_reg_1718) + unsigned(ap_const_lv32_1));
    and_ln284_1_fu_1265_p2 <= (icmp_ln284_11_fu_1253_p2 and icmp_ln284_10_fu_1233_p2);
    and_ln284_2_fu_1271_p2 <= (and_ln284_fu_1259_p2 and and_ln284_1_fu_1265_p2);
    and_ln284_fu_1259_p2 <= (icmp_ln284_fu_1203_p2 and icmp_ln284_1_fu_1213_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_block_state4_assign_proc : process(and_ln284_2_reg_1750, io_acc_block_signal_op198)
    begin
                ap_block_state4 <= ((io_acc_block_signal_op198 = ap_const_logic_0) and (ap_const_lv1_1 = and_ln284_2_reg_1750));
    end process;


    ap_condition_289_assign_proc : process(ap_CS_fsm_state4, and_ln284_2_reg_1750, io_acc_block_signal_op198)
    begin
                ap_condition_289 <= (not(((io_acc_block_signal_op198 = ap_const_logic_0) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) and (ap_const_logic_1 = ap_CS_fsm_state4));
    end process;


    ap_condition_298_assign_proc : process(ap_CS_fsm_state4, and_ln284_2_reg_1750, icmp_ln303_fu_1293_p2, io_acc_block_signal_op198)
    begin
                ap_condition_298 <= (not(((io_acc_block_signal_op198 = ap_const_logic_0) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln303_fu_1293_p2 = ap_const_lv1_1));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_storemerge_phi_fu_252_p4_assign_proc : process(icmp_ln303_reg_1774, icmp_ln307_reg_1783, select_ln313_reg_1787, storemerge_reg_248, ap_CS_fsm_state5)
    begin
        if (((icmp_ln307_reg_1783 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln303_reg_1774 = ap_const_lv1_1))) then 
            ap_phi_mux_storemerge_phi_fu_252_p4 <= select_ln313_reg_1787;
        else 
            ap_phi_mux_storemerge_phi_fu_252_p4 <= storemerge_reg_248;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_start_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_start <= ap_const_logic_1;
        else 
            call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_8u_config19_s_fu_331_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_start <= grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config19_mult_0_0_0_0_0_fu_259_ap_start_reg;
    icmp_ln284_10_fu_1233_p2 <= "1" when (signed(tmp_fu_1223_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_ln284_11_fu_1253_p2 <= "1" when (signed(tmp_4_fu_1243_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_ln284_1_fu_1213_p2 <= "1" when (sY_3 = ap_const_lv32_2) else "0";
    icmp_ln284_fu_1203_p2 <= "1" when (sX_3 = ap_const_lv32_2) else "0";
    icmp_ln303_fu_1293_p2 <= "1" when (pX_3_load_reg_1744 = ap_const_lv32_41) else "0";
    icmp_ln307_fu_1333_p2 <= "1" when (pY_3_load_reg_1738 = ap_const_lv32_41) else "0";
    io_acc_block_signal_op198 <= (res_stream_V_data_3_V_full_n and res_stream_V_data_2_V_full_n and res_stream_V_data_1_V_full_n and res_stream_V_data_0_V_full_n);

    res_stream_V_data_0_V_blk_n_assign_proc : process(res_stream_V_data_0_V_full_n, ap_CS_fsm_state4, and_ln284_2_reg_1750)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) then 
            res_stream_V_data_0_V_blk_n <= res_stream_V_data_0_V_full_n;
        else 
            res_stream_V_data_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_0_V_din <= res_out_0_V_reg_1754;

    res_stream_V_data_0_V_write_assign_proc : process(ap_CS_fsm_state4, and_ln284_2_reg_1750, io_acc_block_signal_op198)
    begin
        if ((not(((io_acc_block_signal_op198 = ap_const_logic_0) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) then 
            res_stream_V_data_0_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_0_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_1_V_blk_n_assign_proc : process(res_stream_V_data_1_V_full_n, ap_CS_fsm_state4, and_ln284_2_reg_1750)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) then 
            res_stream_V_data_1_V_blk_n <= res_stream_V_data_1_V_full_n;
        else 
            res_stream_V_data_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_1_V_din <= res_out_1_V_reg_1759;

    res_stream_V_data_1_V_write_assign_proc : process(ap_CS_fsm_state4, and_ln284_2_reg_1750, io_acc_block_signal_op198)
    begin
        if ((not(((io_acc_block_signal_op198 = ap_const_logic_0) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) then 
            res_stream_V_data_1_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_1_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_2_V_blk_n_assign_proc : process(res_stream_V_data_2_V_full_n, ap_CS_fsm_state4, and_ln284_2_reg_1750)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) then 
            res_stream_V_data_2_V_blk_n <= res_stream_V_data_2_V_full_n;
        else 
            res_stream_V_data_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_2_V_din <= res_out_2_V_reg_1764;

    res_stream_V_data_2_V_write_assign_proc : process(ap_CS_fsm_state4, and_ln284_2_reg_1750, io_acc_block_signal_op198)
    begin
        if ((not(((io_acc_block_signal_op198 = ap_const_logic_0) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) then 
            res_stream_V_data_2_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_2_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_3_V_blk_n_assign_proc : process(res_stream_V_data_3_V_full_n, ap_CS_fsm_state4, and_ln284_2_reg_1750)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) then 
            res_stream_V_data_3_V_blk_n <= res_stream_V_data_3_V_full_n;
        else 
            res_stream_V_data_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_3_V_din <= res_out_3_V_reg_1769;

    res_stream_V_data_3_V_write_assign_proc : process(ap_CS_fsm_state4, and_ln284_2_reg_1750, io_acc_block_signal_op198)
    begin
        if ((not(((io_acc_block_signal_op198 = ap_const_logic_0) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_lv1_1 = and_ln284_2_reg_1750))) then 
            res_stream_V_data_3_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_3_V_write <= ap_const_logic_0;
        end if; 
    end process;

    select_ln313_fu_1354_p3 <= 
        ap_const_lv32_2 when (icmp_ln284_1_reg_1733(0) = '1') else 
        add_ln313_fu_1349_p2;
    select_ln318_fu_1314_p3 <= 
        ap_const_lv32_2 when (icmp_ln284_reg_1723(0) = '1') else 
        add_ln318_fu_1309_p2;
    tmp_4_fu_1243_p4 <= pX_3(31 downto 1);
    tmp_fu_1223_p4 <= pY_3(31 downto 1);
end behav;
