-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_4_2_5_3_0_4u_config8_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    data_V_data_0_V_dout : IN STD_LOGIC_VECTOR (3 downto 0);
    data_V_data_0_V_empty_n : IN STD_LOGIC;
    data_V_data_0_V_read : OUT STD_LOGIC;
    data_V_data_1_V_dout : IN STD_LOGIC_VECTOR (3 downto 0);
    data_V_data_1_V_empty_n : IN STD_LOGIC;
    data_V_data_1_V_read : OUT STD_LOGIC;
    data_V_data_2_V_dout : IN STD_LOGIC_VECTOR (3 downto 0);
    data_V_data_2_V_empty_n : IN STD_LOGIC;
    data_V_data_2_V_read : OUT STD_LOGIC;
    data_V_data_3_V_dout : IN STD_LOGIC_VECTOR (3 downto 0);
    data_V_data_3_V_empty_n : IN STD_LOGIC;
    data_V_data_3_V_read : OUT STD_LOGIC;
    res_V_data_0_V_din : OUT STD_LOGIC_VECTOR (3 downto 0);
    res_V_data_0_V_full_n : IN STD_LOGIC;
    res_V_data_0_V_write : OUT STD_LOGIC;
    res_V_data_1_V_din : OUT STD_LOGIC_VECTOR (3 downto 0);
    res_V_data_1_V_full_n : IN STD_LOGIC;
    res_V_data_1_V_write : OUT STD_LOGIC;
    res_V_data_2_V_din : OUT STD_LOGIC_VECTOR (3 downto 0);
    res_V_data_2_V_full_n : IN STD_LOGIC;
    res_V_data_2_V_write : OUT STD_LOGIC;
    res_V_data_3_V_din : OUT STD_LOGIC_VECTOR (3 downto 0);
    res_V_data_3_V_full_n : IN STD_LOGIC;
    res_V_data_3_V_write : OUT STD_LOGIC );
end;


architecture behav of pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_4_2_5_3_0_4u_config8_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv13_1000 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal pX : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sX : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pY : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sY : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal kernel_data_V_7_4 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_7_5 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_7_6 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_7_7 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_7_12 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_7_13 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_7_14 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal kernel_data_V_7_15 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal line_buffer_Array_V_7_0_0_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_7_0_0_we0 : STD_LOGIC;
    signal line_buffer_Array_V_7_0_0_q0 : STD_LOGIC_VECTOR (3 downto 0);
    signal line_buffer_Array_V_7_0_1_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_7_0_1_we0 : STD_LOGIC;
    signal line_buffer_Array_V_7_0_1_q0 : STD_LOGIC_VECTOR (3 downto 0);
    signal line_buffer_Array_V_7_0_2_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_7_0_2_we0 : STD_LOGIC;
    signal line_buffer_Array_V_7_0_2_q0 : STD_LOGIC_VECTOR (3 downto 0);
    signal line_buffer_Array_V_7_0_3_ce0 : STD_LOGIC;
    signal line_buffer_Array_V_7_0_3_we0 : STD_LOGIC;
    signal line_buffer_Array_V_7_0_3_q0 : STD_LOGIC_VECTOR (3 downto 0);
    signal data_V_data_0_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal icmp_ln241_reg_693 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_V_data_1_V_blk_n : STD_LOGIC;
    signal data_V_data_2_V_blk_n : STD_LOGIC;
    signal data_V_data_3_V_blk_n : STD_LOGIC;
    signal res_V_data_0_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal and_ln191_2_reg_766 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_V_data_1_V_blk_n : STD_LOGIC;
    signal res_V_data_2_V_blk_n : STD_LOGIC;
    signal res_V_data_3_V_blk_n : STD_LOGIC;
    signal indvar_flatten_reg_140 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln241_fu_162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln241_fu_168_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln241_reg_697 : STD_LOGIC_VECTOR (12 downto 0);
    signal pool_window_3_V_reg_702 : STD_LOGIC_VECTOR (3 downto 0);
    signal io_acc_block_signal_op20 : STD_LOGIC;
    signal ap_block_state3_pp0_stage1_iter0 : BOOLEAN;
    signal io_acc_block_signal_op117 : STD_LOGIC;
    signal ap_block_state5_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal pool_window_3_V_1_reg_710 : STD_LOGIC_VECTOR (3 downto 0);
    signal pool_window_3_V_2_reg_718 : STD_LOGIC_VECTOR (3 downto 0);
    signal pool_window_3_V_3_reg_726 : STD_LOGIC_VECTOR (3 downto 0);
    signal pool_window_1_V_reg_734 : STD_LOGIC_VECTOR (3 downto 0);
    signal pool_window_1_V_1_reg_742 : STD_LOGIC_VECTOR (3 downto 0);
    signal pool_window_1_V_2_reg_750 : STD_LOGIC_VECTOR (3 downto 0);
    signal pool_window_1_V_3_reg_758 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln191_2_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln212_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln212_reg_770 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln227_fu_312_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln227_reg_774 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln216_fu_332_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln216_reg_779 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln222_fu_356_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln222_reg_783 : STD_LOGIC_VECTOR (31 downto 0);
    signal pool_window_0_V_reg_788 : STD_LOGIC_VECTOR (3 downto 0);
    signal pool_window_0_V_1_reg_793 : STD_LOGIC_VECTOR (3 downto 0);
    signal pool_window_0_V_2_reg_798 : STD_LOGIC_VECTOR (3 downto 0);
    signal pool_window_0_V_3_reg_803 : STD_LOGIC_VECTOR (3 downto 0);
    signal pool_window_2_V_reg_808 : STD_LOGIC_VECTOR (3 downto 0);
    signal pool_window_2_V_1_reg_813 : STD_LOGIC_VECTOR (3 downto 0);
    signal pool_window_2_V_2_reg_818 : STD_LOGIC_VECTOR (3 downto 0);
    signal pool_window_2_V_3_reg_823 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln66_3_fu_478_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln66_3_reg_828 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln66_7_fu_528_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln66_7_reg_833 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln66_11_fu_578_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln66_11_reg_838 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln66_15_fu_628_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln66_15_reg_843 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_phi_mux_indvar_flatten_phi_fu_144_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_storemerge_i_i_reg_151 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_storemerge_i_i_reg_151 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln225_fu_294_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln220_fu_338_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_sY_load : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_0_V_fu_647_p6 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal tmp_data_1_V_fu_657_p6 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_data_2_V_fu_667_p6 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_data_3_V_fu_677_p6 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln191_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln191_1_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln191_2_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln191_3_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln191_1_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln191_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln227_fu_306_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln222_fu_350_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln1496_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1496_1_fu_448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln66_fu_441_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln66_2_fu_461_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1496_2_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln66_1_fu_453_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln66_fu_474_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln1496_4_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1496_5_fu_498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln66_4_fu_491_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln66_6_fu_511_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1496_6_fu_518_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln66_5_fu_503_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln66_1_fu_524_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln1496_7_fu_536_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1496_8_fu_548_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln66_8_fu_541_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln66_10_fu_561_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1496_9_fu_568_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln66_9_fu_553_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln66_2_fu_574_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln1496_3_fu_586_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1496_10_fu_598_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln66_12_fu_591_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln66_14_fu_611_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1496_11_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln66_13_fu_603_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln66_3_fu_624_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_322 : BOOLEAN;
    signal ap_condition_633 : BOOLEAN;
    signal ap_condition_637 : BOOLEAN;

    component myproject_axi_mux_42_4_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        din2 : IN STD_LOGIC_VECTOR (3 downto 0);
        din3 : IN STD_LOGIC_VECTOR (3 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_4_2_5_3_0_4u_config8_s_line_bufpcA IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (3 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;



begin
    line_buffer_Array_V_7_0_0_U : component pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_4_2_5_3_0_4u_config8_s_line_bufpcA
    generic map (
        DataWidth => 4,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_3F,
        ce0 => line_buffer_Array_V_7_0_0_ce0,
        we0 => line_buffer_Array_V_7_0_0_we0,
        d0 => data_V_data_0_V_dout,
        q0 => line_buffer_Array_V_7_0_0_q0);

    line_buffer_Array_V_7_0_1_U : component pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_4_2_5_3_0_4u_config8_s_line_bufpcA
    generic map (
        DataWidth => 4,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_3F,
        ce0 => line_buffer_Array_V_7_0_1_ce0,
        we0 => line_buffer_Array_V_7_0_1_we0,
        d0 => data_V_data_1_V_dout,
        q0 => line_buffer_Array_V_7_0_1_q0);

    line_buffer_Array_V_7_0_2_U : component pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_4_2_5_3_0_4u_config8_s_line_bufpcA
    generic map (
        DataWidth => 4,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_3F,
        ce0 => line_buffer_Array_V_7_0_2_ce0,
        we0 => line_buffer_Array_V_7_0_2_we0,
        d0 => data_V_data_2_V_dout,
        q0 => line_buffer_Array_V_7_0_2_q0);

    line_buffer_Array_V_7_0_3_U : component pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_4_2_5_3_0_4u_config8_s_line_bufpcA
    generic map (
        DataWidth => 4,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv6_3F,
        ce0 => line_buffer_Array_V_7_0_3_ce0,
        we0 => line_buffer_Array_V_7_0_3_we0,
        d0 => data_V_data_3_V_dout,
        q0 => line_buffer_Array_V_7_0_3_q0);

    myproject_axi_mux_42_4_1_1_U213 : component myproject_axi_mux_42_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        din2_WIDTH => 4,
        din3_WIDTH => 4,
        din4_WIDTH => 2,
        dout_WIDTH => 4)
    port map (
        din0 => pool_window_0_V_reg_788,
        din1 => pool_window_1_V_reg_734,
        din2 => pool_window_2_V_reg_808,
        din3 => pool_window_3_V_reg_702,
        din4 => select_ln66_3_reg_828,
        dout => tmp_data_0_V_fu_647_p6);

    myproject_axi_mux_42_4_1_1_U214 : component myproject_axi_mux_42_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        din2_WIDTH => 4,
        din3_WIDTH => 4,
        din4_WIDTH => 2,
        dout_WIDTH => 4)
    port map (
        din0 => pool_window_0_V_1_reg_793,
        din1 => pool_window_1_V_1_reg_742,
        din2 => pool_window_2_V_1_reg_813,
        din3 => pool_window_3_V_1_reg_710,
        din4 => select_ln66_7_reg_833,
        dout => tmp_data_1_V_fu_657_p6);

    myproject_axi_mux_42_4_1_1_U215 : component myproject_axi_mux_42_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        din2_WIDTH => 4,
        din3_WIDTH => 4,
        din4_WIDTH => 2,
        dout_WIDTH => 4)
    port map (
        din0 => pool_window_0_V_2_reg_798,
        din1 => pool_window_1_V_2_reg_750,
        din2 => pool_window_2_V_2_reg_818,
        din3 => pool_window_3_V_2_reg_718,
        din4 => select_ln66_11_reg_838,
        dout => tmp_data_2_V_fu_667_p6);

    myproject_axi_mux_42_4_1_1_U216 : component myproject_axi_mux_42_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        din2_WIDTH => 4,
        din3_WIDTH => 4,
        din4_WIDTH => 2,
        dout_WIDTH => 4)
    port map (
        din0 => pool_window_0_V_3_reg_803,
        din1 => pool_window_1_V_3_reg_758,
        din2 => pool_window_2_V_3_reg_823,
        din3 => pool_window_3_V_3_reg_726,
        din4 => select_ln66_15_reg_843,
        dout => tmp_data_3_V_fu_677_p6);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_storemerge_i_i_reg_151_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln216_reg_779 = ap_const_lv1_1) and (icmp_ln212_reg_770 = ap_const_lv1_1) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then 
                ap_phi_reg_pp0_iter1_storemerge_i_i_reg_151 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln212_reg_770 = ap_const_lv1_1) and (icmp_ln216_reg_779 = ap_const_lv1_0) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then 
                ap_phi_reg_pp0_iter1_storemerge_i_i_reg_151 <= select_ln222_reg_783;
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                ap_phi_reg_pp0_iter1_storemerge_i_i_reg_151 <= ap_phi_reg_pp0_iter0_storemerge_i_i_reg_151;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then 
                indvar_flatten_reg_140 <= add_ln241_reg_697;
            elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten_reg_140 <= ap_const_lv13_0;
            end if; 
        end if;
    end process;

    pX_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_322)) then
                if ((icmp_ln212_fu_288_p2 = ap_const_lv1_1)) then 
                    pX <= ap_const_lv32_0;
                elsif ((icmp_ln212_fu_288_p2 = ap_const_lv1_0)) then 
                    pX <= add_ln225_fu_294_p2;
                end if;
            end if; 
        end if;
    end process;

    pY_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((icmp_ln241_reg_693 = ap_const_lv1_0)) then
                if ((ap_const_boolean_1 = ap_condition_637)) then 
                    pY <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_633)) then 
                    pY <= add_ln220_fu_338_p2;
                end if;
            end if; 
        end if;
    end process;

    sX_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln212_reg_770 = ap_const_lv1_0))) then 
                sX <= select_ln227_reg_774;
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln212_fu_288_p2 = ap_const_lv1_1) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then 
                sX <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln241_reg_697 <= add_ln241_fu_168_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then
                and_ln191_2_reg_766 <= and_ln191_2_fu_282_p2;
                icmp_ln212_reg_770 <= icmp_ln212_fu_288_p2;
                pool_window_1_V_1_reg_742 <= line_buffer_Array_V_7_0_1_q0;
                pool_window_1_V_2_reg_750 <= line_buffer_Array_V_7_0_2_q0;
                pool_window_1_V_3_reg_758 <= line_buffer_Array_V_7_0_3_q0;
                pool_window_1_V_reg_734 <= line_buffer_Array_V_7_0_0_q0;
                pool_window_3_V_1_reg_710 <= data_V_data_1_V_dout;
                pool_window_3_V_2_reg_718 <= data_V_data_2_V_dout;
                pool_window_3_V_3_reg_726 <= data_V_data_3_V_dout;
                pool_window_3_V_reg_702 <= data_V_data_0_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln212_fu_288_p2 = ap_const_lv1_1) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then
                icmp_ln216_reg_779 <= icmp_ln216_fu_332_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln241_reg_693 <= icmp_ln241_fu_162_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then
                kernel_data_V_7_12 <= pool_window_3_V_reg_702;
                kernel_data_V_7_13 <= pool_window_3_V_1_reg_710;
                kernel_data_V_7_14 <= pool_window_3_V_2_reg_718;
                kernel_data_V_7_15 <= pool_window_3_V_3_reg_726;
                kernel_data_V_7_4 <= pool_window_1_V_reg_734;
                kernel_data_V_7_5 <= pool_window_1_V_1_reg_742;
                kernel_data_V_7_6 <= pool_window_1_V_2_reg_750;
                kernel_data_V_7_7 <= pool_window_1_V_3_reg_758;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then
                pool_window_0_V_1_reg_793 <= kernel_data_V_7_5;
                pool_window_0_V_2_reg_798 <= kernel_data_V_7_6;
                pool_window_0_V_3_reg_803 <= kernel_data_V_7_7;
                pool_window_0_V_reg_788 <= kernel_data_V_7_4;
                pool_window_2_V_1_reg_813 <= kernel_data_V_7_13;
                pool_window_2_V_2_reg_818 <= kernel_data_V_7_14;
                pool_window_2_V_3_reg_823 <= kernel_data_V_7_15;
                pool_window_2_V_reg_808 <= kernel_data_V_7_12;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln212_reg_770 = ap_const_lv1_1))) then
                sY <= ap_phi_reg_pp0_iter1_storemerge_i_i_reg_151;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln212_fu_288_p2 = ap_const_lv1_1) and (icmp_ln216_fu_332_p2 = ap_const_lv1_0) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then
                select_ln222_reg_783 <= select_ln222_fu_356_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln212_fu_288_p2 = ap_const_lv1_0) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then
                select_ln227_reg_774 <= select_ln227_fu_312_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln191_2_reg_766))) then
                select_ln66_11_reg_838 <= select_ln66_11_fu_578_p3;
                select_ln66_15_reg_843 <= select_ln66_15_fu_628_p3;
                select_ln66_3_reg_828 <= select_ln66_3_fu_478_p3;
                select_ln66_7_reg_833 <= select_ln66_7_fu_528_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, icmp_ln241_fu_162_p2, ap_block_pp0_stage0_subdone, ap_block_pp0_stage1_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln241_fu_162_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln241_fu_162_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln220_fu_338_p2 <= std_logic_vector(unsigned(pY) + unsigned(ap_const_lv32_1));
    add_ln222_fu_350_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_sY_load) + unsigned(ap_const_lv32_1));
    add_ln225_fu_294_p2 <= std_logic_vector(unsigned(pX) + unsigned(ap_const_lv32_1));
    add_ln227_fu_306_p2 <= std_logic_vector(unsigned(sX) + unsigned(ap_const_lv32_1));
    add_ln241_fu_168_p2 <= std_logic_vector(unsigned(ap_phi_mux_indvar_flatten_phi_fu_144_p4) + unsigned(ap_const_lv13_1));
    and_ln191_1_fu_276_p2 <= (icmp_ln191_3_fu_264_p2 and icmp_ln191_2_fu_254_p2);
    and_ln191_2_fu_282_p2 <= (and_ln191_fu_270_p2 and and_ln191_1_fu_276_p2);
    and_ln191_fu_270_p2 <= (icmp_ln191_fu_234_p2 and icmp_ln191_1_fu_244_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state6 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln241_reg_693, ap_enable_reg_pp0_iter1, and_ln191_2_reg_766, io_acc_block_signal_op20, io_acc_block_signal_op117)
    begin
                ap_block_pp0_stage1_01001 <= (((io_acc_block_signal_op117 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_lv1_1 = and_ln191_2_reg_766)) or ((io_acc_block_signal_op20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln241_reg_693 = ap_const_lv1_0)));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln241_reg_693, ap_enable_reg_pp0_iter1, and_ln191_2_reg_766, io_acc_block_signal_op20, io_acc_block_signal_op117)
    begin
                ap_block_pp0_stage1_11001 <= (((io_acc_block_signal_op117 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_lv1_1 = and_ln191_2_reg_766)) or ((io_acc_block_signal_op20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln241_reg_693 = ap_const_lv1_0)));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln241_reg_693, ap_enable_reg_pp0_iter1, and_ln191_2_reg_766, io_acc_block_signal_op20, io_acc_block_signal_op117)
    begin
                ap_block_pp0_stage1_subdone <= (((io_acc_block_signal_op117 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_lv1_1 = and_ln191_2_reg_766)) or ((io_acc_block_signal_op20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln241_reg_693 = ap_const_lv1_0)));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage1_iter0_assign_proc : process(icmp_ln241_reg_693, io_acc_block_signal_op20)
    begin
                ap_block_state3_pp0_stage1_iter0 <= ((io_acc_block_signal_op20 = ap_const_logic_0) and (icmp_ln241_reg_693 = ap_const_lv1_0));
    end process;

        ap_block_state4_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_pp0_stage1_iter1_assign_proc : process(and_ln191_2_reg_766, io_acc_block_signal_op117)
    begin
                ap_block_state5_pp0_stage1_iter1 <= ((io_acc_block_signal_op117 = ap_const_logic_0) and (ap_const_lv1_1 = and_ln191_2_reg_766));
    end process;


    ap_condition_322_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, icmp_ln241_reg_693, ap_block_pp0_stage1_11001)
    begin
                ap_condition_322 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln241_reg_693 = ap_const_lv1_0));
    end process;


    ap_condition_633_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, ap_block_pp0_stage1_11001, icmp_ln212_fu_288_p2, icmp_ln216_fu_332_p2)
    begin
                ap_condition_633 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln212_fu_288_p2 = ap_const_lv1_1) and (icmp_ln216_fu_332_p2 = ap_const_lv1_0));
    end process;


    ap_condition_637_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln212_reg_770, icmp_ln216_reg_779)
    begin
                ap_condition_637 <= ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln216_reg_779 = ap_const_lv1_1) and (icmp_ln212_reg_770 = ap_const_lv1_1));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln241_fu_162_p2)
    begin
        if ((icmp_ln241_fu_162_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_indvar_flatten_phi_fu_144_p4_assign_proc : process(icmp_ln241_reg_693, ap_enable_reg_pp0_iter1, indvar_flatten_reg_140, ap_CS_fsm_pp0_stage0, add_ln241_reg_697, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then 
            ap_phi_mux_indvar_flatten_phi_fu_144_p4 <= add_ln241_reg_697;
        else 
            ap_phi_mux_indvar_flatten_phi_fu_144_p4 <= indvar_flatten_reg_140;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_storemerge_i_i_reg_151 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_ready <= internal_ap_ready;

    ap_sig_allocacmp_sY_load_assign_proc : process(sY, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_enable_reg_pp0_iter1, icmp_ln212_reg_770, ap_phi_reg_pp0_iter1_storemerge_i_i_reg_151)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln212_reg_770 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1))) then 
            ap_sig_allocacmp_sY_load <= ap_phi_reg_pp0_iter1_storemerge_i_i_reg_151;
        else 
            ap_sig_allocacmp_sY_load <= sY;
        end if; 
    end process;


    data_V_data_0_V_blk_n_assign_proc : process(data_V_data_0_V_empty_n, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, ap_block_pp0_stage1, icmp_ln241_reg_693)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln241_reg_693 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1))) then 
            data_V_data_0_V_blk_n <= data_V_data_0_V_empty_n;
        else 
            data_V_data_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_0_V_read_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, icmp_ln241_reg_693, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then 
            data_V_data_0_V_read <= ap_const_logic_1;
        else 
            data_V_data_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_1_V_blk_n_assign_proc : process(data_V_data_1_V_empty_n, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, ap_block_pp0_stage1, icmp_ln241_reg_693)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln241_reg_693 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1))) then 
            data_V_data_1_V_blk_n <= data_V_data_1_V_empty_n;
        else 
            data_V_data_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_1_V_read_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, icmp_ln241_reg_693, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then 
            data_V_data_1_V_read <= ap_const_logic_1;
        else 
            data_V_data_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_2_V_blk_n_assign_proc : process(data_V_data_2_V_empty_n, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, ap_block_pp0_stage1, icmp_ln241_reg_693)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln241_reg_693 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1))) then 
            data_V_data_2_V_blk_n <= data_V_data_2_V_empty_n;
        else 
            data_V_data_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_2_V_read_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, icmp_ln241_reg_693, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then 
            data_V_data_2_V_read <= ap_const_logic_1;
        else 
            data_V_data_2_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_3_V_blk_n_assign_proc : process(data_V_data_3_V_empty_n, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, ap_block_pp0_stage1, icmp_ln241_reg_693)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln241_reg_693 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1))) then 
            data_V_data_3_V_blk_n <= data_V_data_3_V_empty_n;
        else 
            data_V_data_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_3_V_read_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, icmp_ln241_reg_693, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then 
            data_V_data_3_V_read <= ap_const_logic_1;
        else 
            data_V_data_3_V_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1496_10_fu_598_p2 <= "1" when (signed(kernel_data_V_7_15) < signed(pool_window_3_V_3_reg_726)) else "0";
    icmp_ln1496_11_fu_618_p2 <= "1" when (signed(select_ln66_12_fu_591_p3) < signed(select_ln66_14_fu_611_p3)) else "0";
    icmp_ln1496_1_fu_448_p2 <= "1" when (signed(kernel_data_V_7_12) < signed(pool_window_3_V_reg_702)) else "0";
    icmp_ln1496_2_fu_468_p2 <= "1" when (signed(select_ln66_fu_441_p3) < signed(select_ln66_2_fu_461_p3)) else "0";
    icmp_ln1496_3_fu_586_p2 <= "1" when (signed(kernel_data_V_7_7) < signed(pool_window_1_V_3_reg_758)) else "0";
    icmp_ln1496_4_fu_486_p2 <= "1" when (signed(kernel_data_V_7_5) < signed(pool_window_1_V_1_reg_742)) else "0";
    icmp_ln1496_5_fu_498_p2 <= "1" when (signed(kernel_data_V_7_13) < signed(pool_window_3_V_1_reg_710)) else "0";
    icmp_ln1496_6_fu_518_p2 <= "1" when (signed(select_ln66_4_fu_491_p3) < signed(select_ln66_6_fu_511_p3)) else "0";
    icmp_ln1496_7_fu_536_p2 <= "1" when (signed(kernel_data_V_7_6) < signed(pool_window_1_V_2_reg_750)) else "0";
    icmp_ln1496_8_fu_548_p2 <= "1" when (signed(kernel_data_V_7_14) < signed(pool_window_3_V_2_reg_718)) else "0";
    icmp_ln1496_9_fu_568_p2 <= "1" when (signed(select_ln66_8_fu_541_p3) < signed(select_ln66_10_fu_561_p3)) else "0";
    icmp_ln1496_fu_436_p2 <= "1" when (signed(kernel_data_V_7_4) < signed(pool_window_1_V_reg_734)) else "0";
    icmp_ln191_1_fu_244_p2 <= "1" when (ap_sig_allocacmp_sY_load = ap_const_lv32_1) else "0";
    icmp_ln191_2_fu_254_p2 <= "1" when (signed(pY) > signed(ap_const_lv32_0)) else "0";
    icmp_ln191_3_fu_264_p2 <= "1" when (signed(pX) > signed(ap_const_lv32_0)) else "0";
    icmp_ln191_fu_234_p2 <= "1" when (sX = ap_const_lv32_1) else "0";
    icmp_ln212_fu_288_p2 <= "1" when (pX = ap_const_lv32_3F) else "0";
    icmp_ln216_fu_332_p2 <= "1" when (pY = ap_const_lv32_3F) else "0";
    icmp_ln241_fu_162_p2 <= "1" when (ap_phi_mux_indvar_flatten_phi_fu_144_p4 = ap_const_lv13_1000) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    io_acc_block_signal_op117 <= (res_V_data_3_V_full_n and res_V_data_2_V_full_n and res_V_data_1_V_full_n and res_V_data_0_V_full_n);
    io_acc_block_signal_op20 <= (data_V_data_3_V_empty_n and data_V_data_2_V_empty_n and data_V_data_1_V_empty_n and data_V_data_0_V_empty_n);

    line_buffer_Array_V_7_0_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, icmp_ln241_reg_693, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then 
            line_buffer_Array_V_7_0_0_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_7_0_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_7_0_0_we0_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, icmp_ln241_reg_693, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then 
            line_buffer_Array_V_7_0_0_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_7_0_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_7_0_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, icmp_ln241_reg_693, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then 
            line_buffer_Array_V_7_0_1_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_7_0_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_7_0_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, icmp_ln241_reg_693, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then 
            line_buffer_Array_V_7_0_1_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_7_0_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_7_0_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, icmp_ln241_reg_693, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then 
            line_buffer_Array_V_7_0_2_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_7_0_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_7_0_2_we0_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, icmp_ln241_reg_693, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then 
            line_buffer_Array_V_7_0_2_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_7_0_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_7_0_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, icmp_ln241_reg_693, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then 
            line_buffer_Array_V_7_0_3_ce0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_7_0_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_Array_V_7_0_3_we0_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, icmp_ln241_reg_693, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln241_reg_693 = ap_const_lv1_0))) then 
            line_buffer_Array_V_7_0_3_we0 <= ap_const_logic_1;
        else 
            line_buffer_Array_V_7_0_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    res_V_data_0_V_blk_n_assign_proc : process(res_V_data_0_V_full_n, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_enable_reg_pp0_iter1, and_ln191_2_reg_766)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_lv1_1 = and_ln191_2_reg_766) and (ap_const_boolean_0 = ap_block_pp0_stage1))) then 
            res_V_data_0_V_blk_n <= res_V_data_0_V_full_n;
        else 
            res_V_data_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_0_V_din <= tmp_data_0_V_fu_647_p6;

    res_V_data_0_V_write_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter1, and_ln191_2_reg_766, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_lv1_1 = and_ln191_2_reg_766))) then 
            res_V_data_0_V_write <= ap_const_logic_1;
        else 
            res_V_data_0_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_1_V_blk_n_assign_proc : process(res_V_data_1_V_full_n, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_enable_reg_pp0_iter1, and_ln191_2_reg_766)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_lv1_1 = and_ln191_2_reg_766) and (ap_const_boolean_0 = ap_block_pp0_stage1))) then 
            res_V_data_1_V_blk_n <= res_V_data_1_V_full_n;
        else 
            res_V_data_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_1_V_din <= tmp_data_1_V_fu_657_p6;

    res_V_data_1_V_write_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter1, and_ln191_2_reg_766, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_lv1_1 = and_ln191_2_reg_766))) then 
            res_V_data_1_V_write <= ap_const_logic_1;
        else 
            res_V_data_1_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_2_V_blk_n_assign_proc : process(res_V_data_2_V_full_n, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_enable_reg_pp0_iter1, and_ln191_2_reg_766)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_lv1_1 = and_ln191_2_reg_766) and (ap_const_boolean_0 = ap_block_pp0_stage1))) then 
            res_V_data_2_V_blk_n <= res_V_data_2_V_full_n;
        else 
            res_V_data_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_2_V_din <= tmp_data_2_V_fu_667_p6;

    res_V_data_2_V_write_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter1, and_ln191_2_reg_766, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_lv1_1 = and_ln191_2_reg_766))) then 
            res_V_data_2_V_write <= ap_const_logic_1;
        else 
            res_V_data_2_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_3_V_blk_n_assign_proc : process(res_V_data_3_V_full_n, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_enable_reg_pp0_iter1, and_ln191_2_reg_766)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_lv1_1 = and_ln191_2_reg_766) and (ap_const_boolean_0 = ap_block_pp0_stage1))) then 
            res_V_data_3_V_blk_n <= res_V_data_3_V_full_n;
        else 
            res_V_data_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_3_V_din <= tmp_data_3_V_fu_677_p6;

    res_V_data_3_V_write_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter1, and_ln191_2_reg_766, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_lv1_1 = and_ln191_2_reg_766))) then 
            res_V_data_3_V_write <= ap_const_logic_1;
        else 
            res_V_data_3_V_write <= ap_const_logic_0;
        end if; 
    end process;

    select_ln222_fu_356_p3 <= 
        ap_const_lv32_0 when (icmp_ln191_1_fu_244_p2(0) = '1') else 
        add_ln222_fu_350_p2;
    select_ln227_fu_312_p3 <= 
        ap_const_lv32_0 when (icmp_ln191_fu_234_p2(0) = '1') else 
        add_ln227_fu_306_p2;
    select_ln66_10_fu_561_p3 <= 
        pool_window_3_V_2_reg_718 when (icmp_ln1496_8_fu_548_p2(0) = '1') else 
        kernel_data_V_7_14;
    select_ln66_11_fu_578_p3 <= 
        select_ln66_9_fu_553_p3 when (icmp_ln1496_9_fu_568_p2(0) = '1') else 
        zext_ln66_2_fu_574_p1;
    select_ln66_12_fu_591_p3 <= 
        pool_window_1_V_3_reg_758 when (icmp_ln1496_3_fu_586_p2(0) = '1') else 
        kernel_data_V_7_7;
    select_ln66_13_fu_603_p3 <= 
        ap_const_lv2_3 when (icmp_ln1496_10_fu_598_p2(0) = '1') else 
        ap_const_lv2_2;
    select_ln66_14_fu_611_p3 <= 
        pool_window_3_V_3_reg_726 when (icmp_ln1496_10_fu_598_p2(0) = '1') else 
        kernel_data_V_7_15;
    select_ln66_15_fu_628_p3 <= 
        select_ln66_13_fu_603_p3 when (icmp_ln1496_11_fu_618_p2(0) = '1') else 
        zext_ln66_3_fu_624_p1;
    select_ln66_1_fu_453_p3 <= 
        ap_const_lv2_3 when (icmp_ln1496_1_fu_448_p2(0) = '1') else 
        ap_const_lv2_2;
    select_ln66_2_fu_461_p3 <= 
        pool_window_3_V_reg_702 when (icmp_ln1496_1_fu_448_p2(0) = '1') else 
        kernel_data_V_7_12;
    select_ln66_3_fu_478_p3 <= 
        select_ln66_1_fu_453_p3 when (icmp_ln1496_2_fu_468_p2(0) = '1') else 
        zext_ln66_fu_474_p1;
    select_ln66_4_fu_491_p3 <= 
        pool_window_1_V_1_reg_742 when (icmp_ln1496_4_fu_486_p2(0) = '1') else 
        kernel_data_V_7_5;
    select_ln66_5_fu_503_p3 <= 
        ap_const_lv2_3 when (icmp_ln1496_5_fu_498_p2(0) = '1') else 
        ap_const_lv2_2;
    select_ln66_6_fu_511_p3 <= 
        pool_window_3_V_1_reg_710 when (icmp_ln1496_5_fu_498_p2(0) = '1') else 
        kernel_data_V_7_13;
    select_ln66_7_fu_528_p3 <= 
        select_ln66_5_fu_503_p3 when (icmp_ln1496_6_fu_518_p2(0) = '1') else 
        zext_ln66_1_fu_524_p1;
    select_ln66_8_fu_541_p3 <= 
        pool_window_1_V_2_reg_750 when (icmp_ln1496_7_fu_536_p2(0) = '1') else 
        kernel_data_V_7_6;
    select_ln66_9_fu_553_p3 <= 
        ap_const_lv2_3 when (icmp_ln1496_8_fu_548_p2(0) = '1') else 
        ap_const_lv2_2;
    select_ln66_fu_441_p3 <= 
        pool_window_1_V_reg_734 when (icmp_ln1496_fu_436_p2(0) = '1') else 
        kernel_data_V_7_4;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln66_1_fu_524_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln1496_4_fu_486_p2),2));
    zext_ln66_2_fu_574_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln1496_7_fu_536_p2),2));
    zext_ln66_3_fu_624_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln1496_3_fu_586_p2),2));
    zext_ln66_fu_474_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln1496_fu_436_p2),2));
end behav;
