-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    kernel_data_V_2_0 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_2 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_3 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_4 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_5 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_6 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_7 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_8 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_9 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_10 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_11 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_12 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_13 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_14 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_15 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_16 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_17 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_18 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_19 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_20 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_21 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_22 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_23 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_24 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_25 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_data_V_2_26 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv5_16 : STD_LOGIC_VECTOR (4 downto 0) := "10110";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv5_13 : STD_LOGIC_VECTOR (4 downto 0) := "10011";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_B : STD_LOGIC_VECTOR (4 downto 0) := "01011";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv5_1D : STD_LOGIC_VECTOR (4 downto 0) := "11101";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_1B : STD_LOGIC_VECTOR (4 downto 0) := "11011";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv16_FFF1 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111110001";
    constant ap_const_lv16_18 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000011000";
    constant ap_const_lv16_2D : STD_LOGIC_VECTOR (15 downto 0) := "0000000000101101";
    constant ap_const_lv16_C : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001100";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv7_6B : STD_LOGIC_VECTOR (6 downto 0) := "1101011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln135_fu_589_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal outidx7_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal outidx7_ce0 : STD_LOGIC;
    signal outidx7_q0 : STD_LOGIC_VECTOR (1 downto 0);
    signal w2_V_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal w2_V_ce0 : STD_LOGIC;
    signal w2_V_q0 : STD_LOGIC_VECTOR (9 downto 0);
    signal in_index_0_i30_reg_202 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_index29_reg_217 : STD_LOGIC_VECTOR (6 downto 0);
    signal acc_0_V_020_reg_290 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_1_V_019_reg_305 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_2_V_018_reg_320 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_3_V_017_reg_335 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_0_V_write_assign28_reg_365 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_1_V_write_assign26_reg_379 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_2_V_write_assign24_reg_393 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_3_V_write_assign22_reg_407 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_index_fu_571_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal w_index_reg_787 : STD_LOGIC_VECTOR (6 downto 0);
    signal in_index_fu_577_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_index_reg_797 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln154_fu_583_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln154_reg_802 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln135_reg_807 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln135_reg_807_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln135_reg_807_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln135_reg_807_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln135_reg_807_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln135_reg_807_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_index_reg_811 : STD_LOGIC_VECTOR (1 downto 0);
    signal out_index_reg_811_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal out_index_reg_811_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal out_index_reg_811_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal out_index_reg_811_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln145_fu_595_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal w2_V_load_reg_955 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln154_fu_707_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal grp_fu_776_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal r_V_reg_975 : STD_LOGIC_VECTOR (25 downto 0);
    signal acc_0_V_fu_742_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_0_V_reg_980 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_phi_mux_in_index_0_i30_phi_fu_206_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_mux_w_index29_phi_fu_221_p6 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_phi_reg_pp0_iter0_UnifiedRetVal_i_i_reg_231 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_UnifiedRetVal_i_i_reg_231 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_acc_0_V_020_phi_fu_294_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_acc_0_V_1_phi_fu_479_p8 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_acc_1_V_019_phi_fu_309_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_acc_1_V_1_phi_fu_461_p8 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_acc_2_V_018_phi_fu_324_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_acc_2_V_1_phi_fu_443_p8 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_acc_3_V_017_phi_fu_339_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_acc_3_V_1_phi_fu_425_p8 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_p_0_01_i_phi_fu_551_p8 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_p_0_13_i_phi_fu_533_p8 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_p_0_25_i_phi_fu_515_p8 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_p_0_37_i_phi_fu_497_p8 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter6_acc_3_V_1_reg_421 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter6_acc_2_V_1_reg_439 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter6_acc_1_V_1_reg_457 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter6_acc_0_V_1_reg_475 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter6_p_0_37_i_reg_493 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter6_p_0_25_i_reg_511 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter6_p_0_13_i_reg_529 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter6_p_0_01_i_reg_547 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln139_fu_565_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln1_fu_720_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_729_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_776_ce : STD_LOGIC;
    signal ap_return_0_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_return_1_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_return_2_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_return_3_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_0to5 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_346 : BOOLEAN;
    signal ap_condition_311 : BOOLEAN;
    signal ap_condition_319 : BOOLEAN;

    component myproject_axi_mux_42_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component myproject_axi_mul_mul_16s_10s_26_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_outidx7 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_w2_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;



begin
    outidx7_U : component dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_outidx7
    generic map (
        DataWidth => 2,
        AddressRange => 108,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => outidx7_address0,
        ce0 => outidx7_ce0,
        q0 => outidx7_q0);

    w2_V_U : component dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_w2_V
    generic map (
        DataWidth => 10,
        AddressRange => 108,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => w2_V_address0,
        ce0 => w2_V_ce0,
        q0 => w2_V_q0);

    myproject_axi_mux_42_16_1_1_U40 : component myproject_axi_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => ap_phi_mux_acc_0_V_020_phi_fu_294_p6,
        din1 => ap_phi_mux_acc_1_V_019_phi_fu_309_p6,
        din2 => ap_phi_mux_acc_2_V_018_phi_fu_324_p6,
        din3 => ap_phi_mux_acc_3_V_017_phi_fu_339_p6,
        din4 => out_index_reg_811_pp0_iter4_reg,
        dout => tmp_fu_729_p6);

    myproject_axi_mul_mul_16s_10s_26_3_1_U41 : component myproject_axi_mul_mul_16s_10s_26_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231,
        din1 => w2_V_load_reg_955,
        ce => grp_fu_776_ce,
        dout => grp_fu_776_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_return_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_0_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
                    ap_return_0_preg <= ap_phi_mux_p_0_01_i_phi_fu_551_p8;
                end if; 
            end if;
        end if;
    end process;


    ap_return_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_1_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
                    ap_return_1_preg <= ap_phi_mux_p_0_13_i_phi_fu_533_p8;
                end if; 
            end if;
        end if;
    end process;


    ap_return_2_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_2_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
                    ap_return_2_preg <= ap_phi_mux_p_0_25_i_phi_fu_515_p8;
                end if; 
            end if;
        end if;
    end process;


    ap_return_3_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_3_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
                    ap_return_3_preg <= ap_phi_mux_p_0_37_i_phi_fu_497_p8;
                end if; 
            end if;
        end if;
    end process;


    acc_0_V_020_reg_290_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_0))) then 
                acc_0_V_020_reg_290 <= ap_phi_mux_acc_0_V_1_phi_fu_479_p8;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                acc_0_V_020_reg_290 <= ap_const_lv16_FFF1;
            end if; 
        end if;
    end process;

    acc_1_V_019_reg_305_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_0))) then 
                acc_1_V_019_reg_305 <= ap_phi_mux_acc_1_V_1_phi_fu_461_p8;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                acc_1_V_019_reg_305 <= ap_const_lv16_18;
            end if; 
        end if;
    end process;

    acc_2_V_018_reg_320_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_0))) then 
                acc_2_V_018_reg_320 <= ap_phi_mux_acc_2_V_1_phi_fu_443_p8;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                acc_2_V_018_reg_320 <= ap_const_lv16_2D;
            end if; 
        end if;
    end process;

    acc_3_V_017_reg_335_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_0))) then 
                acc_3_V_017_reg_335 <= ap_phi_mux_acc_3_V_1_phi_fu_425_p8;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                acc_3_V_017_reg_335 <= ap_const_lv16_C;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_319)) then
                if ((ap_const_boolean_1 = ap_condition_311)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_26;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_19)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_25;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_18)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_24;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_17)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_23;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_16)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_22;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_15)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_21;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_14)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_20;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_13)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_19;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_12)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_18;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_11)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_17;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_10)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_16;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_F)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_15;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_E)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_14;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_D)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_13;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_C)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_12;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_B)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_11;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_A)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_10;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_9)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_9;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_8)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_8;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_7)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_7;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_6)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_6;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_5)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_5;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_4)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_4;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_3)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_3;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_2)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_2;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_1)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_1;
                elsif ((trunc_ln145_fu_595_p1 = ap_const_lv5_0)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= kernel_data_V_2_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_UnifiedRetVal_i_i_reg_231 <= ap_phi_reg_pp0_iter1_UnifiedRetVal_i_i_reg_231;
                end if;
            end if; 
        end if;
    end process;

    in_index_0_i30_reg_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln135_reg_807 = ap_const_lv1_0))) then 
                in_index_0_i30_reg_202 <= select_ln154_fu_707_p3;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_reg_807 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                in_index_0_i30_reg_202 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    res_0_V_write_assign28_reg_365_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_0))) then 
                res_0_V_write_assign28_reg_365 <= ap_phi_mux_p_0_01_i_phi_fu_551_p8;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                res_0_V_write_assign28_reg_365 <= ap_const_lv16_FFF1;
            end if; 
        end if;
    end process;

    res_1_V_write_assign26_reg_379_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_0))) then 
                res_1_V_write_assign26_reg_379 <= ap_phi_mux_p_0_13_i_phi_fu_533_p8;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                res_1_V_write_assign26_reg_379 <= ap_const_lv16_18;
            end if; 
        end if;
    end process;

    res_2_V_write_assign24_reg_393_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_0))) then 
                res_2_V_write_assign24_reg_393 <= ap_phi_mux_p_0_25_i_phi_fu_515_p8;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                res_2_V_write_assign24_reg_393 <= ap_const_lv16_2D;
            end if; 
        end if;
    end process;

    res_3_V_write_assign22_reg_407_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_0))) then 
                res_3_V_write_assign22_reg_407 <= ap_phi_mux_p_0_37_i_phi_fu_497_p8;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                res_3_V_write_assign22_reg_407 <= ap_const_lv16_C;
            end if; 
        end if;
    end process;

    w_index29_reg_217_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln135_reg_807 = ap_const_lv1_0))) then 
                w_index29_reg_217 <= w_index_reg_787;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_reg_807 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                w_index29_reg_217 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                acc_0_V_reg_980 <= acc_0_V_fu_742_p2;
                icmp_ln135_reg_807_pp0_iter2_reg <= icmp_ln135_reg_807_pp0_iter1_reg;
                icmp_ln135_reg_807_pp0_iter3_reg <= icmp_ln135_reg_807_pp0_iter2_reg;
                icmp_ln135_reg_807_pp0_iter4_reg <= icmp_ln135_reg_807_pp0_iter3_reg;
                icmp_ln135_reg_807_pp0_iter5_reg <= icmp_ln135_reg_807_pp0_iter4_reg;
                out_index_reg_811_pp0_iter2_reg <= out_index_reg_811;
                out_index_reg_811_pp0_iter3_reg <= out_index_reg_811_pp0_iter2_reg;
                out_index_reg_811_pp0_iter4_reg <= out_index_reg_811_pp0_iter3_reg;
                out_index_reg_811_pp0_iter5_reg <= out_index_reg_811_pp0_iter4_reg;
                r_V_reg_975 <= grp_fu_776_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter1_UnifiedRetVal_i_i_reg_231 <= ap_phi_reg_pp0_iter0_UnifiedRetVal_i_i_reg_231;
                w_index_reg_787 <= w_index_fu_571_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln135_reg_807 <= icmp_ln135_fu_589_p2;
                icmp_ln135_reg_807_pp0_iter1_reg <= icmp_ln135_reg_807;
                icmp_ln154_reg_802 <= icmp_ln154_fu_583_p2;
                in_index_reg_797 <= in_index_fu_577_p2;
                out_index_reg_811 <= outidx7_q0;
                w2_V_load_reg_955 <= w2_V_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_reset_idle_pp0 = ap_const_logic_0)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_reset_idle_pp0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    acc_0_V_fu_742_p2 <= std_logic_vector(unsigned(trunc_ln1_fu_720_p4) + unsigned(tmp_fu_729_p6));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_311_assign_proc : process(trunc_ln145_fu_595_p1)
    begin
                ap_condition_311 <= ((trunc_ln145_fu_595_p1 = ap_const_lv5_1A) or ((trunc_ln145_fu_595_p1 = ap_const_lv5_1B) or ((trunc_ln145_fu_595_p1 = ap_const_lv5_1C) or ((trunc_ln145_fu_595_p1 = ap_const_lv5_1D) or ((trunc_ln145_fu_595_p1 = ap_const_lv5_1E) or (trunc_ln145_fu_595_p1 = ap_const_lv5_1F))))));
    end process;


    ap_condition_319_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
                ap_condition_319 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_346_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
                ap_condition_346 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_block_pp0_stage0_11001, icmp_ln135_reg_807_pp0_iter5_reg, ap_enable_reg_pp0_iter6)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to5_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to5 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_acc_0_V_020_phi_fu_294_p6_assign_proc : process(acc_0_V_020_reg_290, icmp_ln135_reg_807_pp0_iter5_reg, ap_enable_reg_pp0_iter6, ap_block_pp0_stage0, ap_phi_mux_acc_0_V_1_phi_fu_479_p8)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then
            if ((icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1)) then 
                ap_phi_mux_acc_0_V_020_phi_fu_294_p6 <= ap_const_lv16_FFF1;
            elsif ((icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_0)) then 
                ap_phi_mux_acc_0_V_020_phi_fu_294_p6 <= ap_phi_mux_acc_0_V_1_phi_fu_479_p8;
            else 
                ap_phi_mux_acc_0_V_020_phi_fu_294_p6 <= acc_0_V_020_reg_290;
            end if;
        else 
            ap_phi_mux_acc_0_V_020_phi_fu_294_p6 <= acc_0_V_020_reg_290;
        end if; 
    end process;


    ap_phi_mux_acc_0_V_1_phi_fu_479_p8_assign_proc : process(acc_0_V_020_reg_290, out_index_reg_811_pp0_iter5_reg, acc_0_V_reg_980, ap_phi_reg_pp0_iter6_acc_0_V_1_reg_475)
    begin
        if ((out_index_reg_811_pp0_iter5_reg = ap_const_lv2_0)) then 
            ap_phi_mux_acc_0_V_1_phi_fu_479_p8 <= acc_0_V_reg_980;
        elsif (((out_index_reg_811_pp0_iter5_reg = ap_const_lv2_1) or (out_index_reg_811_pp0_iter5_reg = ap_const_lv2_2) or (out_index_reg_811_pp0_iter5_reg = ap_const_lv2_3))) then 
            ap_phi_mux_acc_0_V_1_phi_fu_479_p8 <= acc_0_V_020_reg_290;
        else 
            ap_phi_mux_acc_0_V_1_phi_fu_479_p8 <= ap_phi_reg_pp0_iter6_acc_0_V_1_reg_475;
        end if; 
    end process;


    ap_phi_mux_acc_1_V_019_phi_fu_309_p6_assign_proc : process(acc_1_V_019_reg_305, icmp_ln135_reg_807_pp0_iter5_reg, ap_enable_reg_pp0_iter6, ap_block_pp0_stage0, ap_phi_mux_acc_1_V_1_phi_fu_461_p8)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then
            if ((icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1)) then 
                ap_phi_mux_acc_1_V_019_phi_fu_309_p6 <= ap_const_lv16_18;
            elsif ((icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_0)) then 
                ap_phi_mux_acc_1_V_019_phi_fu_309_p6 <= ap_phi_mux_acc_1_V_1_phi_fu_461_p8;
            else 
                ap_phi_mux_acc_1_V_019_phi_fu_309_p6 <= acc_1_V_019_reg_305;
            end if;
        else 
            ap_phi_mux_acc_1_V_019_phi_fu_309_p6 <= acc_1_V_019_reg_305;
        end if; 
    end process;


    ap_phi_mux_acc_1_V_1_phi_fu_461_p8_assign_proc : process(acc_1_V_019_reg_305, out_index_reg_811_pp0_iter5_reg, acc_0_V_reg_980, ap_phi_reg_pp0_iter6_acc_1_V_1_reg_457)
    begin
        if ((out_index_reg_811_pp0_iter5_reg = ap_const_lv2_1)) then 
            ap_phi_mux_acc_1_V_1_phi_fu_461_p8 <= acc_0_V_reg_980;
        elsif (((out_index_reg_811_pp0_iter5_reg = ap_const_lv2_0) or (out_index_reg_811_pp0_iter5_reg = ap_const_lv2_2) or (out_index_reg_811_pp0_iter5_reg = ap_const_lv2_3))) then 
            ap_phi_mux_acc_1_V_1_phi_fu_461_p8 <= acc_1_V_019_reg_305;
        else 
            ap_phi_mux_acc_1_V_1_phi_fu_461_p8 <= ap_phi_reg_pp0_iter6_acc_1_V_1_reg_457;
        end if; 
    end process;


    ap_phi_mux_acc_2_V_018_phi_fu_324_p6_assign_proc : process(acc_2_V_018_reg_320, icmp_ln135_reg_807_pp0_iter5_reg, ap_enable_reg_pp0_iter6, ap_block_pp0_stage0, ap_phi_mux_acc_2_V_1_phi_fu_443_p8)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then
            if ((icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1)) then 
                ap_phi_mux_acc_2_V_018_phi_fu_324_p6 <= ap_const_lv16_2D;
            elsif ((icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_0)) then 
                ap_phi_mux_acc_2_V_018_phi_fu_324_p6 <= ap_phi_mux_acc_2_V_1_phi_fu_443_p8;
            else 
                ap_phi_mux_acc_2_V_018_phi_fu_324_p6 <= acc_2_V_018_reg_320;
            end if;
        else 
            ap_phi_mux_acc_2_V_018_phi_fu_324_p6 <= acc_2_V_018_reg_320;
        end if; 
    end process;


    ap_phi_mux_acc_2_V_1_phi_fu_443_p8_assign_proc : process(acc_2_V_018_reg_320, out_index_reg_811_pp0_iter5_reg, acc_0_V_reg_980, ap_phi_reg_pp0_iter6_acc_2_V_1_reg_439)
    begin
        if ((out_index_reg_811_pp0_iter5_reg = ap_const_lv2_2)) then 
            ap_phi_mux_acc_2_V_1_phi_fu_443_p8 <= acc_0_V_reg_980;
        elsif (((out_index_reg_811_pp0_iter5_reg = ap_const_lv2_0) or (out_index_reg_811_pp0_iter5_reg = ap_const_lv2_1) or (out_index_reg_811_pp0_iter5_reg = ap_const_lv2_3))) then 
            ap_phi_mux_acc_2_V_1_phi_fu_443_p8 <= acc_2_V_018_reg_320;
        else 
            ap_phi_mux_acc_2_V_1_phi_fu_443_p8 <= ap_phi_reg_pp0_iter6_acc_2_V_1_reg_439;
        end if; 
    end process;


    ap_phi_mux_acc_3_V_017_phi_fu_339_p6_assign_proc : process(acc_3_V_017_reg_335, icmp_ln135_reg_807_pp0_iter5_reg, ap_enable_reg_pp0_iter6, ap_block_pp0_stage0, ap_phi_mux_acc_3_V_1_phi_fu_425_p8)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then
            if ((icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1)) then 
                ap_phi_mux_acc_3_V_017_phi_fu_339_p6 <= ap_const_lv16_C;
            elsif ((icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_0)) then 
                ap_phi_mux_acc_3_V_017_phi_fu_339_p6 <= ap_phi_mux_acc_3_V_1_phi_fu_425_p8;
            else 
                ap_phi_mux_acc_3_V_017_phi_fu_339_p6 <= acc_3_V_017_reg_335;
            end if;
        else 
            ap_phi_mux_acc_3_V_017_phi_fu_339_p6 <= acc_3_V_017_reg_335;
        end if; 
    end process;


    ap_phi_mux_acc_3_V_1_phi_fu_425_p8_assign_proc : process(acc_3_V_017_reg_335, out_index_reg_811_pp0_iter5_reg, acc_0_V_reg_980, ap_phi_reg_pp0_iter6_acc_3_V_1_reg_421)
    begin
        if (((out_index_reg_811_pp0_iter5_reg = ap_const_lv2_0) or (out_index_reg_811_pp0_iter5_reg = ap_const_lv2_1) or (out_index_reg_811_pp0_iter5_reg = ap_const_lv2_2))) then 
            ap_phi_mux_acc_3_V_1_phi_fu_425_p8 <= acc_3_V_017_reg_335;
        elsif ((out_index_reg_811_pp0_iter5_reg = ap_const_lv2_3)) then 
            ap_phi_mux_acc_3_V_1_phi_fu_425_p8 <= acc_0_V_reg_980;
        else 
            ap_phi_mux_acc_3_V_1_phi_fu_425_p8 <= ap_phi_reg_pp0_iter6_acc_3_V_1_reg_421;
        end if; 
    end process;


    ap_phi_mux_in_index_0_i30_phi_fu_206_p6_assign_proc : process(in_index_0_i30_reg_202, icmp_ln135_reg_807, select_ln154_fu_707_p3, ap_condition_346)
    begin
        if ((ap_const_boolean_1 = ap_condition_346)) then
            if ((icmp_ln135_reg_807 = ap_const_lv1_1)) then 
                ap_phi_mux_in_index_0_i30_phi_fu_206_p6 <= ap_const_lv32_0;
            elsif ((icmp_ln135_reg_807 = ap_const_lv1_0)) then 
                ap_phi_mux_in_index_0_i30_phi_fu_206_p6 <= select_ln154_fu_707_p3;
            else 
                ap_phi_mux_in_index_0_i30_phi_fu_206_p6 <= in_index_0_i30_reg_202;
            end if;
        else 
            ap_phi_mux_in_index_0_i30_phi_fu_206_p6 <= in_index_0_i30_reg_202;
        end if; 
    end process;


    ap_phi_mux_p_0_01_i_phi_fu_551_p8_assign_proc : process(res_0_V_write_assign28_reg_365, out_index_reg_811_pp0_iter5_reg, acc_0_V_reg_980, ap_phi_reg_pp0_iter6_p_0_01_i_reg_547)
    begin
        if ((out_index_reg_811_pp0_iter5_reg = ap_const_lv2_0)) then 
            ap_phi_mux_p_0_01_i_phi_fu_551_p8 <= acc_0_V_reg_980;
        elsif (((out_index_reg_811_pp0_iter5_reg = ap_const_lv2_1) or (out_index_reg_811_pp0_iter5_reg = ap_const_lv2_2) or (out_index_reg_811_pp0_iter5_reg = ap_const_lv2_3))) then 
            ap_phi_mux_p_0_01_i_phi_fu_551_p8 <= res_0_V_write_assign28_reg_365;
        else 
            ap_phi_mux_p_0_01_i_phi_fu_551_p8 <= ap_phi_reg_pp0_iter6_p_0_01_i_reg_547;
        end if; 
    end process;


    ap_phi_mux_p_0_13_i_phi_fu_533_p8_assign_proc : process(res_1_V_write_assign26_reg_379, out_index_reg_811_pp0_iter5_reg, acc_0_V_reg_980, ap_phi_reg_pp0_iter6_p_0_13_i_reg_529)
    begin
        if ((out_index_reg_811_pp0_iter5_reg = ap_const_lv2_1)) then 
            ap_phi_mux_p_0_13_i_phi_fu_533_p8 <= acc_0_V_reg_980;
        elsif (((out_index_reg_811_pp0_iter5_reg = ap_const_lv2_0) or (out_index_reg_811_pp0_iter5_reg = ap_const_lv2_2) or (out_index_reg_811_pp0_iter5_reg = ap_const_lv2_3))) then 
            ap_phi_mux_p_0_13_i_phi_fu_533_p8 <= res_1_V_write_assign26_reg_379;
        else 
            ap_phi_mux_p_0_13_i_phi_fu_533_p8 <= ap_phi_reg_pp0_iter6_p_0_13_i_reg_529;
        end if; 
    end process;


    ap_phi_mux_p_0_25_i_phi_fu_515_p8_assign_proc : process(res_2_V_write_assign24_reg_393, out_index_reg_811_pp0_iter5_reg, acc_0_V_reg_980, ap_phi_reg_pp0_iter6_p_0_25_i_reg_511)
    begin
        if ((out_index_reg_811_pp0_iter5_reg = ap_const_lv2_2)) then 
            ap_phi_mux_p_0_25_i_phi_fu_515_p8 <= acc_0_V_reg_980;
        elsif (((out_index_reg_811_pp0_iter5_reg = ap_const_lv2_0) or (out_index_reg_811_pp0_iter5_reg = ap_const_lv2_1) or (out_index_reg_811_pp0_iter5_reg = ap_const_lv2_3))) then 
            ap_phi_mux_p_0_25_i_phi_fu_515_p8 <= res_2_V_write_assign24_reg_393;
        else 
            ap_phi_mux_p_0_25_i_phi_fu_515_p8 <= ap_phi_reg_pp0_iter6_p_0_25_i_reg_511;
        end if; 
    end process;


    ap_phi_mux_p_0_37_i_phi_fu_497_p8_assign_proc : process(res_3_V_write_assign22_reg_407, out_index_reg_811_pp0_iter5_reg, acc_0_V_reg_980, ap_phi_reg_pp0_iter6_p_0_37_i_reg_493)
    begin
        if (((out_index_reg_811_pp0_iter5_reg = ap_const_lv2_0) or (out_index_reg_811_pp0_iter5_reg = ap_const_lv2_1) or (out_index_reg_811_pp0_iter5_reg = ap_const_lv2_2))) then 
            ap_phi_mux_p_0_37_i_phi_fu_497_p8 <= res_3_V_write_assign22_reg_407;
        elsif ((out_index_reg_811_pp0_iter5_reg = ap_const_lv2_3)) then 
            ap_phi_mux_p_0_37_i_phi_fu_497_p8 <= acc_0_V_reg_980;
        else 
            ap_phi_mux_p_0_37_i_phi_fu_497_p8 <= ap_phi_reg_pp0_iter6_p_0_37_i_reg_493;
        end if; 
    end process;


    ap_phi_mux_w_index29_phi_fu_221_p6_assign_proc : process(w_index29_reg_217, w_index_reg_787, icmp_ln135_reg_807, ap_condition_346)
    begin
        if ((ap_const_boolean_1 = ap_condition_346)) then
            if ((icmp_ln135_reg_807 = ap_const_lv1_1)) then 
                ap_phi_mux_w_index29_phi_fu_221_p6 <= ap_const_lv7_0;
            elsif ((icmp_ln135_reg_807 = ap_const_lv1_0)) then 
                ap_phi_mux_w_index29_phi_fu_221_p6 <= w_index_reg_787;
            else 
                ap_phi_mux_w_index29_phi_fu_221_p6 <= w_index29_reg_217;
            end if;
        else 
            ap_phi_mux_w_index29_phi_fu_221_p6 <= w_index29_reg_217;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_UnifiedRetVal_i_i_reg_231 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter6_acc_0_V_1_reg_475 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter6_acc_1_V_1_reg_457 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter6_acc_2_V_1_reg_439 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter6_acc_3_V_1_reg_421 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter6_p_0_01_i_reg_547 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter6_p_0_13_i_reg_529 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter6_p_0_25_i_reg_511 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter6_p_0_37_i_reg_493 <= "XXXXXXXXXXXXXXXX";

    ap_ready_assign_proc : process(icmp_ln135_fu_589_p2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_fu_589_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to5)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to5 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_0_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln135_reg_807_pp0_iter5_reg, ap_enable_reg_pp0_iter6, ap_phi_mux_p_0_01_i_phi_fu_551_p8, ap_return_0_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            ap_return_0 <= ap_phi_mux_p_0_01_i_phi_fu_551_p8;
        else 
            ap_return_0 <= ap_return_0_preg;
        end if; 
    end process;


    ap_return_1_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln135_reg_807_pp0_iter5_reg, ap_enable_reg_pp0_iter6, ap_phi_mux_p_0_13_i_phi_fu_533_p8, ap_return_1_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            ap_return_1 <= ap_phi_mux_p_0_13_i_phi_fu_533_p8;
        else 
            ap_return_1 <= ap_return_1_preg;
        end if; 
    end process;


    ap_return_2_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln135_reg_807_pp0_iter5_reg, ap_enable_reg_pp0_iter6, ap_phi_mux_p_0_25_i_phi_fu_515_p8, ap_return_2_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            ap_return_2 <= ap_phi_mux_p_0_25_i_phi_fu_515_p8;
        else 
            ap_return_2 <= ap_return_2_preg;
        end if; 
    end process;


    ap_return_3_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln135_reg_807_pp0_iter5_reg, ap_enable_reg_pp0_iter6, ap_phi_mux_p_0_37_i_phi_fu_497_p8, ap_return_3_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_reg_807_pp0_iter5_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            ap_return_3 <= ap_phi_mux_p_0_37_i_phi_fu_497_p8;
        else 
            ap_return_3 <= ap_return_3_preg;
        end if; 
    end process;


    grp_fu_776_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_776_ce <= ap_const_logic_1;
        else 
            grp_fu_776_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln135_fu_589_p2 <= "1" when (ap_phi_mux_w_index29_phi_fu_221_p6 = ap_const_lv7_6B) else "0";
    icmp_ln154_fu_583_p2 <= "1" when (signed(in_index_fu_577_p2) > signed(ap_const_lv32_1A)) else "0";
    in_index_fu_577_p2 <= std_logic_vector(unsigned(ap_phi_mux_in_index_0_i30_phi_fu_206_p6) + unsigned(ap_const_lv32_1));
    outidx7_address0 <= zext_ln139_fu_565_p1(7 - 1 downto 0);

    outidx7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            outidx7_ce0 <= ap_const_logic_1;
        else 
            outidx7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln154_fu_707_p3 <= 
        ap_const_lv32_0 when (icmp_ln154_reg_802(0) = '1') else 
        in_index_reg_797;
    trunc_ln145_fu_595_p1 <= in_index_0_i30_reg_202(5 - 1 downto 0);
    trunc_ln1_fu_720_p4 <= r_V_reg_975(25 downto 10);
    w2_V_address0 <= zext_ln139_fu_565_p1(7 - 1 downto 0);

    w2_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            w2_V_ce0 <= ap_const_logic_1;
        else 
            w2_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    w_index_fu_571_p2 <= std_logic_vector(unsigned(ap_const_lv7_1) + unsigned(ap_phi_mux_w_index29_phi_fu_221_p6));
    zext_ln139_fu_565_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_w_index29_phi_fu_221_p6),64));
end behav;
