// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _compute_output_buffer_2d_array_array_ap_fixed_4_2_5_3_0_4u_config5_s_HH_
#define _compute_output_buffer_2d_array_array_ap_fixed_4_2_5_3_0_4u_config5_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config5_mult_0_0_0_0_0.h"
#include "shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s.h"

namespace ap_rtl {

struct compute_output_buffer_2d_array_array_ap_fixed_4_2_5_3_0_4u_config5_s : public sc_module {
    // Port declarations 22
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<4> > in_elem_data_0_V_read;
    sc_in< sc_lv<4> > in_elem_data_1_V_read;
    sc_in< sc_lv<4> > in_elem_data_2_V_read;
    sc_in< sc_lv<4> > in_elem_data_3_V_read;
    sc_out< sc_lv<4> > res_stream_V_data_0_V_din;
    sc_in< sc_logic > res_stream_V_data_0_V_full_n;
    sc_out< sc_logic > res_stream_V_data_0_V_write;
    sc_out< sc_lv<4> > res_stream_V_data_1_V_din;
    sc_in< sc_logic > res_stream_V_data_1_V_full_n;
    sc_out< sc_logic > res_stream_V_data_1_V_write;
    sc_out< sc_lv<4> > res_stream_V_data_2_V_din;
    sc_in< sc_logic > res_stream_V_data_2_V_full_n;
    sc_out< sc_logic > res_stream_V_data_2_V_write;
    sc_out< sc_lv<4> > res_stream_V_data_3_V_din;
    sc_in< sc_logic > res_stream_V_data_3_V_full_n;
    sc_out< sc_logic > res_stream_V_data_3_V_write;


    // Module declarations
    compute_output_buffer_2d_array_array_ap_fixed_4_2_5_3_0_4u_config5_s(sc_module_name name);
    SC_HAS_PROCESS(compute_output_buffer_2d_array_array_ap_fixed_4_2_5_3_0_4u_config5_s);

    ~compute_output_buffer_2d_array_array_ap_fixed_4_2_5_3_0_4u_config5_s();

    sc_trace_file* mVcdFile;

    dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config5_mult_0_0_0_0_0* grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config5_mult_0_0_0_0_0_fu_169;
    shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s* call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209;
    sc_signal< sc_lv<5> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<4> > kernel_data_V_5_4;
    sc_signal< sc_lv<4> > kernel_data_V_5_5;
    sc_signal< sc_lv<4> > kernel_data_V_5_6;
    sc_signal< sc_lv<4> > kernel_data_V_5_7;
    sc_signal< sc_lv<4> > kernel_data_V_5_8;
    sc_signal< sc_lv<4> > kernel_data_V_5_9;
    sc_signal< sc_lv<4> > kernel_data_V_5_10;
    sc_signal< sc_lv<4> > kernel_data_V_5_11;
    sc_signal< sc_lv<4> > kernel_data_V_5_16;
    sc_signal< sc_lv<4> > kernel_data_V_5_17;
    sc_signal< sc_lv<4> > kernel_data_V_5_18;
    sc_signal< sc_lv<4> > kernel_data_V_5_19;
    sc_signal< sc_lv<4> > kernel_data_V_5_20;
    sc_signal< sc_lv<4> > kernel_data_V_5_21;
    sc_signal< sc_lv<4> > kernel_data_V_5_22;
    sc_signal< sc_lv<4> > kernel_data_V_5_23;
    sc_signal< sc_lv<4> > kernel_data_V_5_28;
    sc_signal< sc_lv<4> > kernel_data_V_5_29;
    sc_signal< sc_lv<4> > kernel_data_V_5_30;
    sc_signal< sc_lv<4> > kernel_data_V_5_31;
    sc_signal< sc_lv<4> > kernel_data_V_5_32;
    sc_signal< sc_lv<4> > kernel_data_V_5_33;
    sc_signal< sc_lv<4> > kernel_data_V_5_34;
    sc_signal< sc_lv<4> > kernel_data_V_5_35;
    sc_signal< sc_lv<32> > sX_4;
    sc_signal< sc_lv<32> > sY_4;
    sc_signal< sc_lv<32> > pY_4;
    sc_signal< sc_lv<32> > pX_4;
    sc_signal< sc_logic > res_stream_V_data_0_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > and_ln284_2_reg_1060;
    sc_signal< sc_logic > res_stream_V_data_1_V_blk_n;
    sc_signal< sc_logic > res_stream_V_data_2_V_blk_n;
    sc_signal< sc_logic > res_stream_V_data_3_V_blk_n;
    sc_signal< sc_lv<4> > kernel_data_V_5_27_ret_reg_848;
    sc_signal< sc_lv<4> > kernel_data_V_5_26_ret_reg_853;
    sc_signal< sc_lv<4> > kernel_data_V_5_25_ret_reg_858;
    sc_signal< sc_lv<4> > kernel_data_V_5_24_ret_reg_863;
    sc_signal< sc_lv<4> > kernel_data_V_5_15_ret_reg_868;
    sc_signal< sc_lv<4> > kernel_data_V_5_14_ret_reg_873;
    sc_signal< sc_lv<4> > kernel_data_V_5_13_ret_reg_878;
    sc_signal< sc_lv<4> > kernel_data_V_5_12_ret_reg_883;
    sc_signal< sc_lv<4> > kernel_data_V_5_3_ret_reg_888;
    sc_signal< sc_lv<4> > kernel_data_V_5_2_ret_reg_893;
    sc_signal< sc_lv<4> > kernel_data_V_5_1_ret_reg_898;
    sc_signal< sc_lv<4> > kernel_data_V_5_0_ret_reg_903;
    sc_signal< sc_lv<4> > kernel_data_V_5_4_ret_reg_908;
    sc_signal< sc_lv<4> > kernel_data_V_5_5_ret_reg_913;
    sc_signal< sc_lv<4> > kernel_data_V_5_6_ret_reg_918;
    sc_signal< sc_lv<4> > kernel_data_V_5_7_ret_reg_923;
    sc_signal< sc_lv<4> > kernel_data_V_5_8_ret_reg_928;
    sc_signal< sc_lv<4> > kernel_data_V_5_9_ret_reg_933;
    sc_signal< sc_lv<4> > kernel_data_V_5_10_ret_reg_938;
    sc_signal< sc_lv<4> > kernel_data_V_5_11_ret_reg_943;
    sc_signal< sc_lv<4> > kernel_data_V_5_16_ret_reg_948;
    sc_signal< sc_lv<4> > kernel_data_V_5_17_ret_reg_953;
    sc_signal< sc_lv<4> > kernel_data_V_5_18_ret_reg_958;
    sc_signal< sc_lv<4> > kernel_data_V_5_19_ret_reg_963;
    sc_signal< sc_lv<4> > kernel_data_V_5_20_ret_reg_968;
    sc_signal< sc_lv<4> > kernel_data_V_5_21_ret_reg_973;
    sc_signal< sc_lv<4> > kernel_data_V_5_22_ret_reg_978;
    sc_signal< sc_lv<4> > kernel_data_V_5_23_ret_reg_983;
    sc_signal< sc_lv<4> > kernel_data_V_5_28_ret_reg_988;
    sc_signal< sc_lv<4> > kernel_data_V_5_29_ret_reg_993;
    sc_signal< sc_lv<4> > kernel_data_V_5_30_ret_reg_998;
    sc_signal< sc_lv<4> > kernel_data_V_5_31_ret_reg_1003;
    sc_signal< sc_lv<4> > kernel_data_V_5_32_ret_reg_1008;
    sc_signal< sc_lv<4> > kernel_data_V_5_33_ret_reg_1013;
    sc_signal< sc_lv<4> > kernel_data_V_5_34_ret_reg_1018;
    sc_signal< sc_lv<4> > kernel_data_V_5_35_ret_reg_1023;
    sc_signal< sc_lv<32> > sX_4_load_reg_1028;
    sc_signal< sc_lv<1> > icmp_ln284_fu_673_p2;
    sc_signal< sc_lv<1> > icmp_ln284_reg_1033;
    sc_signal< sc_lv<32> > sY_4_load_reg_1038;
    sc_signal< sc_lv<1> > icmp_ln284_1_fu_683_p2;
    sc_signal< sc_lv<1> > icmp_ln284_1_reg_1043;
    sc_signal< sc_lv<32> > pY_4_load_reg_1048;
    sc_signal< sc_lv<32> > pX_4_load_reg_1054;
    sc_signal< sc_lv<1> > and_ln284_2_fu_741_p2;
    sc_signal< sc_lv<4> > res_out_0_V_reg_1064;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config5_mult_0_0_0_0_0_fu_169_ap_ready;
    sc_signal< sc_logic > grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config5_mult_0_0_0_0_0_fu_169_ap_done;
    sc_signal< sc_lv<4> > res_out_1_V_reg_1069;
    sc_signal< sc_lv<4> > res_out_2_V_reg_1074;
    sc_signal< sc_lv<4> > res_out_3_V_reg_1079;
    sc_signal< sc_lv<1> > icmp_ln303_fu_763_p2;
    sc_signal< sc_lv<1> > icmp_ln303_reg_1084;
    sc_signal< sc_logic > io_acc_block_signal_op119;
    sc_signal< bool > ap_block_state4;
    sc_signal< sc_lv<32> > select_ln318_fu_784_p3;
    sc_signal< sc_lv<32> > select_ln318_reg_1088;
    sc_signal< sc_lv<1> > icmp_ln307_fu_803_p2;
    sc_signal< sc_lv<1> > icmp_ln307_reg_1093;
    sc_signal< sc_lv<32> > select_ln313_fu_824_p3;
    sc_signal< sc_lv<32> > select_ln313_reg_1097;
    sc_signal< sc_logic > grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config5_mult_0_0_0_0_0_fu_169_ap_start;
    sc_signal< sc_logic > grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config5_mult_0_0_0_0_0_fu_169_ap_idle;
    sc_signal< sc_lv<4> > grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config5_mult_0_0_0_0_0_fu_169_ap_return_0;
    sc_signal< sc_lv<4> > grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config5_mult_0_0_0_0_0_fu_169_ap_return_1;
    sc_signal< sc_lv<4> > grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config5_mult_0_0_0_0_0_fu_169_ap_return_2;
    sc_signal< sc_lv<4> > grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config5_mult_0_0_0_0_0_fu_169_ap_return_3;
    sc_signal< sc_logic > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_start;
    sc_signal< sc_logic > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_done;
    sc_signal< sc_logic > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_idle;
    sc_signal< sc_logic > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_ready;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_0;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_1;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_2;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_3;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_4;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_5;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_6;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_7;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_8;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_9;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_10;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_11;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_12;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_13;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_14;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_15;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_16;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_17;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_18;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_19;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_20;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_21;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_22;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_23;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_24;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_25;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_26;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_27;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_28;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_29;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_30;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_31;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_32;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_33;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_34;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_return_35;
    sc_signal< sc_lv<32> > ap_phi_mux_storemerge_phi_fu_162_p4;
    sc_signal< sc_lv<32> > storemerge_reg_158;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config5_mult_0_0_0_0_0_fu_169_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<32> > add_ln311_fu_808_p2;
    sc_signal< sc_lv<32> > add_ln316_fu_768_p2;
    sc_signal< sc_lv<31> > tmp_fu_693_p4;
    sc_signal< sc_lv<31> > tmp_1_fu_713_p4;
    sc_signal< sc_lv<1> > icmp_ln284_2_fu_703_p2;
    sc_signal< sc_lv<1> > icmp_ln284_3_fu_723_p2;
    sc_signal< sc_lv<1> > and_ln284_1_fu_735_p2;
    sc_signal< sc_lv<1> > and_ln284_fu_729_p2;
    sc_signal< sc_lv<32> > add_ln318_fu_779_p2;
    sc_signal< sc_lv<32> > add_ln313_fu_819_p2;
    sc_signal< sc_lv<5> > ap_NS_fsm;
    sc_signal< bool > ap_condition_200;
    sc_signal< bool > ap_condition_209;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<5> ap_ST_fsm_state1;
    static const sc_lv<5> ap_ST_fsm_state2;
    static const sc_lv<5> ap_ST_fsm_state3;
    static const sc_lv<5> ap_ST_fsm_state4;
    static const sc_lv<5> ap_ST_fsm_state5;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<31> ap_const_lv31_0;
    static const sc_lv<32> ap_const_lv32_41;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln311_fu_808_p2();
    void thread_add_ln313_fu_819_p2();
    void thread_add_ln316_fu_768_p2();
    void thread_add_ln318_fu_779_p2();
    void thread_and_ln284_1_fu_735_p2();
    void thread_and_ln284_2_fu_741_p2();
    void thread_and_ln284_fu_729_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_block_state4();
    void thread_ap_condition_200();
    void thread_ap_condition_209();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_storemerge_phi_fu_162_p4();
    void thread_ap_ready();
    void thread_call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_4u_config5_s_fu_209_ap_start();
    void thread_grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config5_mult_0_0_0_0_0_fu_169_ap_start();
    void thread_icmp_ln284_1_fu_683_p2();
    void thread_icmp_ln284_2_fu_703_p2();
    void thread_icmp_ln284_3_fu_723_p2();
    void thread_icmp_ln284_fu_673_p2();
    void thread_icmp_ln303_fu_763_p2();
    void thread_icmp_ln307_fu_803_p2();
    void thread_io_acc_block_signal_op119();
    void thread_res_stream_V_data_0_V_blk_n();
    void thread_res_stream_V_data_0_V_din();
    void thread_res_stream_V_data_0_V_write();
    void thread_res_stream_V_data_1_V_blk_n();
    void thread_res_stream_V_data_1_V_din();
    void thread_res_stream_V_data_1_V_write();
    void thread_res_stream_V_data_2_V_blk_n();
    void thread_res_stream_V_data_2_V_din();
    void thread_res_stream_V_data_2_V_write();
    void thread_res_stream_V_data_3_V_blk_n();
    void thread_res_stream_V_data_3_V_din();
    void thread_res_stream_V_data_3_V_write();
    void thread_select_ln313_fu_824_p3();
    void thread_select_ln318_fu_784_p3();
    void thread_tmp_1_fu_713_p4();
    void thread_tmp_fu_693_p4();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
