// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_4u_config2_s_HH_
#define _compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_4u_config2_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0.h"
#include "shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s.h"

namespace ap_rtl {

struct compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_4u_config2_s : public sc_module {
    // Port declarations 21
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<16> > in_elem_data_0_V_read;
    sc_in< sc_lv<16> > in_elem_data_1_V_read;
    sc_in< sc_lv<16> > in_elem_data_2_V_read;
    sc_out< sc_lv<16> > res_stream_V_data_0_V_din;
    sc_in< sc_logic > res_stream_V_data_0_V_full_n;
    sc_out< sc_logic > res_stream_V_data_0_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_1_V_din;
    sc_in< sc_logic > res_stream_V_data_1_V_full_n;
    sc_out< sc_logic > res_stream_V_data_1_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_2_V_din;
    sc_in< sc_logic > res_stream_V_data_2_V_full_n;
    sc_out< sc_logic > res_stream_V_data_2_V_write;
    sc_out< sc_lv<16> > res_stream_V_data_3_V_din;
    sc_in< sc_logic > res_stream_V_data_3_V_full_n;
    sc_out< sc_logic > res_stream_V_data_3_V_write;


    // Module declarations
    compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_4u_config2_s(sc_module_name name);
    SC_HAS_PROCESS(compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_4u_config2_s);

    ~compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_4u_config2_s();

    sc_trace_file* mVcdFile;

    dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0* grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_167;
    shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s* call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<16> > kernel_data_V_2_3;
    sc_signal< sc_lv<16> > kernel_data_V_2_4;
    sc_signal< sc_lv<16> > kernel_data_V_2_5;
    sc_signal< sc_lv<16> > kernel_data_V_2_6;
    sc_signal< sc_lv<16> > kernel_data_V_2_7;
    sc_signal< sc_lv<16> > kernel_data_V_2_8;
    sc_signal< sc_lv<16> > kernel_data_V_2_12;
    sc_signal< sc_lv<16> > kernel_data_V_2_13;
    sc_signal< sc_lv<16> > kernel_data_V_2_14;
    sc_signal< sc_lv<16> > kernel_data_V_2_15;
    sc_signal< sc_lv<16> > kernel_data_V_2_16;
    sc_signal< sc_lv<16> > kernel_data_V_2_17;
    sc_signal< sc_lv<16> > kernel_data_V_2_21;
    sc_signal< sc_lv<16> > kernel_data_V_2_22;
    sc_signal< sc_lv<16> > kernel_data_V_2_23;
    sc_signal< sc_lv<16> > kernel_data_V_2_24;
    sc_signal< sc_lv<16> > kernel_data_V_2_25;
    sc_signal< sc_lv<16> > kernel_data_V_2_26;
    sc_signal< sc_lv<16> > kernel_data_V_2_0;
    sc_signal< sc_lv<16> > kernel_data_V_2_1;
    sc_signal< sc_lv<16> > kernel_data_V_2_2;
    sc_signal< sc_lv<16> > kernel_data_V_2_9;
    sc_signal< sc_lv<16> > kernel_data_V_2_10;
    sc_signal< sc_lv<16> > kernel_data_V_2_11;
    sc_signal< sc_lv<16> > kernel_data_V_2_18;
    sc_signal< sc_lv<16> > kernel_data_V_2_19;
    sc_signal< sc_lv<16> > kernel_data_V_2_20;
    sc_signal< sc_lv<32> > sX_7;
    sc_signal< sc_lv<32> > sY_7;
    sc_signal< sc_lv<32> > pY_7;
    sc_signal< sc_lv<32> > pX_7;
    sc_signal< sc_logic > res_stream_V_data_0_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > and_ln284_6_reg_844;
    sc_signal< sc_logic > res_stream_V_data_1_V_blk_n;
    sc_signal< sc_logic > res_stream_V_data_2_V_blk_n;
    sc_signal< sc_logic > res_stream_V_data_3_V_blk_n;
    sc_signal< sc_lv<32> > sX_7_load_reg_812;
    sc_signal< sc_lv<1> > icmp_ln284_fu_633_p2;
    sc_signal< sc_lv<1> > icmp_ln284_reg_817;
    sc_signal< sc_lv<32> > sY_7_load_reg_822;
    sc_signal< sc_lv<1> > icmp_ln284_7_fu_643_p2;
    sc_signal< sc_lv<1> > icmp_ln284_7_reg_827;
    sc_signal< sc_lv<32> > pY_7_load_reg_832;
    sc_signal< sc_lv<32> > pX_7_load_reg_838;
    sc_signal< sc_lv<1> > and_ln284_6_fu_701_p2;
    sc_signal< sc_lv<1> > icmp_ln303_fu_727_p2;
    sc_signal< sc_lv<1> > icmp_ln303_reg_848;
    sc_signal< sc_logic > io_acc_block_signal_op104;
    sc_signal< bool > ap_block_state2;
    sc_signal< sc_logic > grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_167_ap_ready;
    sc_signal< sc_logic > grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_167_ap_done;
    sc_signal< bool > ap_block_state2_on_subcall_done;
    sc_signal< sc_lv<32> > select_ln318_fu_748_p3;
    sc_signal< sc_lv<32> > select_ln318_reg_852;
    sc_signal< sc_lv<1> > icmp_ln307_fu_767_p2;
    sc_signal< sc_lv<1> > icmp_ln307_reg_857;
    sc_signal< sc_lv<32> > select_ln313_fu_788_p3;
    sc_signal< sc_lv<32> > select_ln313_reg_861;
    sc_signal< sc_logic > grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_167_ap_start;
    sc_signal< sc_logic > grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_167_ap_idle;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_167_ap_return_0;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_167_ap_return_1;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_167_ap_return_2;
    sc_signal< sc_lv<16> > grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_167_ap_return_3;
    sc_signal< sc_logic > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_start;
    sc_signal< sc_logic > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_done;
    sc_signal< sc_logic > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_idle;
    sc_signal< sc_logic > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_ready;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_0;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_1;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_2;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_3;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_4;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_5;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_6;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_7;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_8;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_9;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_10;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_11;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_12;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_13;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_14;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_15;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_16;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_17;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_18;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_19;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_20;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_21;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_22;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_23;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_24;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_25;
    sc_signal< sc_lv<16> > call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_return_26;
    sc_signal< sc_lv<32> > ap_phi_mux_storemerge_phi_fu_160_p4;
    sc_signal< sc_lv<32> > storemerge_reg_156;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_167_ap_start_reg;
    sc_signal< sc_lv<32> > add_ln311_fu_772_p2;
    sc_signal< sc_lv<32> > add_ln316_fu_732_p2;
    sc_signal< sc_lv<31> > tmp_7_fu_653_p4;
    sc_signal< sc_lv<31> > tmp_8_fu_673_p4;
    sc_signal< sc_lv<1> > icmp_ln284_8_fu_663_p2;
    sc_signal< sc_lv<1> > icmp_ln284_9_fu_683_p2;
    sc_signal< sc_lv<1> > and_ln284_5_fu_695_p2;
    sc_signal< sc_lv<1> > and_ln284_fu_689_p2;
    sc_signal< sc_lv<32> > add_ln318_fu_743_p2;
    sc_signal< sc_lv<32> > add_ln313_fu_783_p2;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< bool > ap_condition_117;
    sc_signal< bool > ap_condition_126;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_state2;
    static const sc_lv<3> ap_ST_fsm_state3;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<31> ap_const_lv31_0;
    static const sc_lv<32> ap_const_lv32_21;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln311_fu_772_p2();
    void thread_add_ln313_fu_783_p2();
    void thread_add_ln316_fu_732_p2();
    void thread_add_ln318_fu_743_p2();
    void thread_and_ln284_5_fu_695_p2();
    void thread_and_ln284_6_fu_701_p2();
    void thread_and_ln284_fu_689_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_block_state2();
    void thread_ap_block_state2_on_subcall_done();
    void thread_ap_condition_117();
    void thread_ap_condition_126();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_storemerge_phi_fu_160_p4();
    void thread_ap_ready();
    void thread_call_ret3_shift_line_buffer_array_ap_fixed_16_6_5_3_0_3u_config2_s_fu_229_ap_start();
    void thread_grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_167_ap_start();
    void thread_icmp_ln284_7_fu_643_p2();
    void thread_icmp_ln284_8_fu_663_p2();
    void thread_icmp_ln284_9_fu_683_p2();
    void thread_icmp_ln284_fu_633_p2();
    void thread_icmp_ln303_fu_727_p2();
    void thread_icmp_ln307_fu_767_p2();
    void thread_io_acc_block_signal_op104();
    void thread_res_stream_V_data_0_V_blk_n();
    void thread_res_stream_V_data_0_V_din();
    void thread_res_stream_V_data_0_V_write();
    void thread_res_stream_V_data_1_V_blk_n();
    void thread_res_stream_V_data_1_V_din();
    void thread_res_stream_V_data_1_V_write();
    void thread_res_stream_V_data_2_V_blk_n();
    void thread_res_stream_V_data_2_V_din();
    void thread_res_stream_V_data_2_V_write();
    void thread_res_stream_V_data_3_V_blk_n();
    void thread_res_stream_V_data_3_V_din();
    void thread_res_stream_V_data_3_V_write();
    void thread_select_ln313_fu_788_p3();
    void thread_select_ln318_fu_748_p3();
    void thread_tmp_7_fu_653_p4();
    void thread_tmp_8_fu_673_p4();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
