// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_ST_fsm_state1 = "1";
const sc_lv<3> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_ST_fsm_state9 = "100";
const sc_lv<32> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_boolean_1 = true;
const sc_lv<32> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv32_1 = "1";
const bool sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_boolean_0 = false;
const sc_lv<1> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv1_0 = "0";
const sc_lv<1> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv1_1 = "1";
const sc_lv<11> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv11_0 = "00000000000";
const sc_lv<11> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv11_400 = "10000000000";
const sc_lv<11> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv11_1 = "1";
const sc_lv<32> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv32_4 = "100";
const sc_lv<32> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv32_F = "1111";
const sc_lv<6> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv6_0 = "000000";
const sc_lv<10> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv10_0 = "0000000000";
const sc_lv<26> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv26_3FFFFF1 = "11111111111111111111110001";
const sc_lv<13> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv13_1 = "1";
const sc_lv<13> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv13_200 = "1000000000";
const sc_lv<10> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv10_200 = "1000000000";
const sc_lv<32> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv32_C = "1100";
const sc_lv<32> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv32_A = "1010";
const sc_lv<3> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv3_0 = "000";
const sc_lv<10> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv10_3FF = "1111111111";
const sc_lv<32> sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::ap_const_lv32_2 = "10";

sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sigmoid_table1_U = new sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s_sigmoid_table1("sigmoid_table1_U");
    sigmoid_table1_U->clk(ap_clk);
    sigmoid_table1_U->reset(ap_rst);
    sigmoid_table1_U->address0(sigmoid_table1_address0);
    sigmoid_table1_U->ce0(sigmoid_table1_ce0);
    sigmoid_table1_U->q0(sigmoid_table1_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln700_fu_179_p2);
    sensitive << ( sext_ln850_fu_170_p1 );

    SC_METHOD(thread_add_ln91_fu_203_p2);
    sensitive << ( select_ln850_reg_298 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( data_V_data_V_empty_n );
    sensitive << ( res_V_data_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln80_reg_274 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( icmp_ln80_reg_274_pp0_iter5_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( data_V_data_V_empty_n );
    sensitive << ( res_V_data_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln80_reg_274 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( icmp_ln80_reg_274_pp0_iter5_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( data_V_data_V_empty_n );
    sensitive << ( res_V_data_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln80_reg_274 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( icmp_ln80_reg_274_pp0_iter5_reg );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);
    sensitive << ( data_V_data_V_empty_n );
    sensitive << ( icmp_ln80_reg_274 );

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter6);
    sensitive << ( res_V_data_V_full_n );
    sensitive << ( icmp_ln80_reg_274_pp0_iter5_reg );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln80_fu_123_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_data_V_data_V_blk_n);
    sensitive << ( data_V_data_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln80_reg_274 );

    SC_METHOD(thread_data_V_data_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln80_reg_274 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_i_fu_129_p2);
    sensitive << ( i_0_reg_112 );

    SC_METHOD(thread_icmp_ln80_fu_123_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( i_0_reg_112 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln850_fu_173_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln80_reg_274_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( shl_ln_fu_163_p3 );

    SC_METHOD(thread_icmp_ln851_fu_157_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln80_reg_274 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( p_Result_3_i_i_i_fu_149_p3 );

    SC_METHOD(thread_icmp_ln94_fu_232_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln80_reg_274_pp0_iter2_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( tmp_2_fu_222_p4 );

    SC_METHOD(thread_or_ln92_fu_252_p2);
    sensitive << ( tmp_1_fu_214_p3 );
    sensitive << ( icmp_ln94_fu_232_p2 );

    SC_METHOD(thread_p_Result_3_i_i_i_fu_149_p3);
    sensitive << ( trunc_ln851_fu_145_p1 );

    SC_METHOD(thread_res_V_data_V_blk_n);
    sensitive << ( res_V_data_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( icmp_ln80_reg_274_pp0_iter5_reg );

    SC_METHOD(thread_res_V_data_V_din);
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( icmp_ln80_reg_274_pp0_iter5_reg );
    sensitive << ( sigmoid_table1_load_reg_314 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_V_write);
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( icmp_ln80_reg_274_pp0_iter5_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_select_ln850_fu_192_p3);
    sensitive << ( sext_ln850_fu_170_p1 );
    sensitive << ( icmp_ln850_fu_173_p2 );
    sensitive << ( select_ln851_fu_185_p3 );

    SC_METHOD(thread_select_ln851_fu_185_p3);
    sensitive << ( icmp_ln851_reg_293 );
    sensitive << ( sext_ln850_fu_170_p1 );
    sensitive << ( add_ln700_fu_179_p2 );

    SC_METHOD(thread_select_ln92_1_fu_258_p3);
    sensitive << ( or_ln92_fu_252_p2 );
    sensitive << ( select_ln92_fu_244_p3 );
    sensitive << ( xor_ln91_fu_208_p2 );

    SC_METHOD(thread_select_ln92_fu_244_p3);
    sensitive << ( xor_ln92_fu_238_p2 );

    SC_METHOD(thread_sext_ln850_fu_170_p1);
    sensitive << ( tmp_s_reg_288 );

    SC_METHOD(thread_shl_ln_fu_163_p3);
    sensitive << ( tmp_data_0_V_reg_283 );

    SC_METHOD(thread_sigmoid_table1_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( zext_ln96_fu_266_p1 );

    SC_METHOD(thread_sigmoid_table1_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_METHOD(thread_tmp_1_fu_214_p3);
    sensitive << ( add_ln91_fu_203_p2 );

    SC_METHOD(thread_tmp_2_fu_222_p4);
    sensitive << ( add_ln91_fu_203_p2 );

    SC_METHOD(thread_trunc_ln851_fu_145_p1);
    sensitive << ( data_V_data_V_dout );

    SC_METHOD(thread_trunc_ln91_fu_200_p1);
    sensitive << ( select_ln850_reg_298 );

    SC_METHOD(thread_xor_ln91_fu_208_p2);
    sensitive << ( trunc_ln91_fu_200_p1 );

    SC_METHOD(thread_xor_ln92_fu_238_p2);
    sensitive << ( tmp_1_fu_214_p3 );

    SC_METHOD(thread_zext_ln96_fu_266_p1);
    sensitive << ( select_ln92_1_reg_304 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( icmp_ln80_fu_123_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_V_data_V_dout, "(port)data_V_data_V_dout");
    sc_trace(mVcdFile, data_V_data_V_empty_n, "(port)data_V_data_V_empty_n");
    sc_trace(mVcdFile, data_V_data_V_read, "(port)data_V_data_V_read");
    sc_trace(mVcdFile, res_V_data_V_din, "(port)res_V_data_V_din");
    sc_trace(mVcdFile, res_V_data_V_full_n, "(port)res_V_data_V_full_n");
    sc_trace(mVcdFile, res_V_data_V_write, "(port)res_V_data_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, sigmoid_table1_address0, "sigmoid_table1_address0");
    sc_trace(mVcdFile, sigmoid_table1_ce0, "sigmoid_table1_ce0");
    sc_trace(mVcdFile, sigmoid_table1_q0, "sigmoid_table1_q0");
    sc_trace(mVcdFile, data_V_data_V_blk_n, "data_V_data_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln80_reg_274, "icmp_ln80_reg_274");
    sc_trace(mVcdFile, res_V_data_V_blk_n, "res_V_data_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, icmp_ln80_reg_274_pp0_iter5_reg, "icmp_ln80_reg_274_pp0_iter5_reg");
    sc_trace(mVcdFile, i_0_reg_112, "i_0_reg_112");
    sc_trace(mVcdFile, icmp_ln80_fu_123_p2, "icmp_ln80_fu_123_p2");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter3, "ap_block_state5_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter4, "ap_block_state6_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter5, "ap_block_state7_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter6, "ap_block_state8_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln80_reg_274_pp0_iter1_reg, "icmp_ln80_reg_274_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln80_reg_274_pp0_iter2_reg, "icmp_ln80_reg_274_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln80_reg_274_pp0_iter3_reg, "icmp_ln80_reg_274_pp0_iter3_reg");
    sc_trace(mVcdFile, icmp_ln80_reg_274_pp0_iter4_reg, "icmp_ln80_reg_274_pp0_iter4_reg");
    sc_trace(mVcdFile, i_fu_129_p2, "i_fu_129_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_data_0_V_reg_283, "tmp_data_0_V_reg_283");
    sc_trace(mVcdFile, tmp_s_reg_288, "tmp_s_reg_288");
    sc_trace(mVcdFile, icmp_ln851_fu_157_p2, "icmp_ln851_fu_157_p2");
    sc_trace(mVcdFile, icmp_ln851_reg_293, "icmp_ln851_reg_293");
    sc_trace(mVcdFile, select_ln850_fu_192_p3, "select_ln850_fu_192_p3");
    sc_trace(mVcdFile, select_ln850_reg_298, "select_ln850_reg_298");
    sc_trace(mVcdFile, select_ln92_1_fu_258_p3, "select_ln92_1_fu_258_p3");
    sc_trace(mVcdFile, select_ln92_1_reg_304, "select_ln92_1_reg_304");
    sc_trace(mVcdFile, sigmoid_table1_load_reg_314, "sigmoid_table1_load_reg_314");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, zext_ln96_fu_266_p1, "zext_ln96_fu_266_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, trunc_ln851_fu_145_p1, "trunc_ln851_fu_145_p1");
    sc_trace(mVcdFile, p_Result_3_i_i_i_fu_149_p3, "p_Result_3_i_i_i_fu_149_p3");
    sc_trace(mVcdFile, shl_ln_fu_163_p3, "shl_ln_fu_163_p3");
    sc_trace(mVcdFile, sext_ln850_fu_170_p1, "sext_ln850_fu_170_p1");
    sc_trace(mVcdFile, add_ln700_fu_179_p2, "add_ln700_fu_179_p2");
    sc_trace(mVcdFile, icmp_ln850_fu_173_p2, "icmp_ln850_fu_173_p2");
    sc_trace(mVcdFile, select_ln851_fu_185_p3, "select_ln851_fu_185_p3");
    sc_trace(mVcdFile, trunc_ln91_fu_200_p1, "trunc_ln91_fu_200_p1");
    sc_trace(mVcdFile, add_ln91_fu_203_p2, "add_ln91_fu_203_p2");
    sc_trace(mVcdFile, tmp_2_fu_222_p4, "tmp_2_fu_222_p4");
    sc_trace(mVcdFile, tmp_1_fu_214_p3, "tmp_1_fu_214_p3");
    sc_trace(mVcdFile, xor_ln92_fu_238_p2, "xor_ln92_fu_238_p2");
    sc_trace(mVcdFile, icmp_ln94_fu_232_p2, "icmp_ln94_fu_232_p2");
    sc_trace(mVcdFile, or_ln92_fu_252_p2, "or_ln92_fu_252_p2");
    sc_trace(mVcdFile, select_ln92_fu_244_p3, "select_ln92_fu_244_p3");
    sc_trace(mVcdFile, xor_ln91_fu_208_p2, "xor_ln91_fu_208_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::~sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete sigmoid_table1_U;
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter6 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_fu_123_p2.read()))) {
        i_0_reg_112 = i_fu_129_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_0_reg_112 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln80_reg_274 = icmp_ln80_fu_123_p2.read();
        icmp_ln80_reg_274_pp0_iter1_reg = icmp_ln80_reg_274.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        icmp_ln80_reg_274_pp0_iter2_reg = icmp_ln80_reg_274_pp0_iter1_reg.read();
        icmp_ln80_reg_274_pp0_iter3_reg = icmp_ln80_reg_274_pp0_iter2_reg.read();
        icmp_ln80_reg_274_pp0_iter4_reg = icmp_ln80_reg_274_pp0_iter3_reg.read();
        icmp_ln80_reg_274_pp0_iter5_reg = icmp_ln80_reg_274_pp0_iter4_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(icmp_ln80_reg_274.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln851_reg_293 = icmp_ln851_fu_157_p2.read();
        tmp_data_0_V_reg_283 = data_V_data_V_dout.read();
        tmp_s_reg_288 = data_V_data_V_dout.read().range(15, 4);
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_274_pp0_iter1_reg.read()))) {
        select_ln850_reg_298 = select_ln850_fu_192_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_274_pp0_iter2_reg.read()))) {
        select_ln92_1_reg_304 = select_ln92_1_fu_258_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_274_pp0_iter4_reg.read()))) {
        sigmoid_table1_load_reg_314 = sigmoid_table1_q0.read();
    }
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_add_ln700_fu_179_p2() {
    add_ln700_fu_179_p2 = (!ap_const_lv13_1.is_01() || !sext_ln850_fu_170_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_1) + sc_bigint<13>(sext_ln850_fu_170_p1.read()));
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_add_ln91_fu_203_p2() {
    add_ln91_fu_203_p2 = (!ap_const_lv13_200.is_01() || !select_ln850_reg_298.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_200) + sc_biguint<13>(select_ln850_reg_298.read()));
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[2];
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln80_reg_274.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, data_V_data_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_274_pp0_iter5_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_V_data_V_full_n.read())));
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln80_reg_274.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, data_V_data_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_274_pp0_iter5_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_V_data_V_full_n.read())));
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln80_reg_274.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, data_V_data_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_274_pp0_iter5_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_V_data_V_full_n.read())));
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = (esl_seteq<1,1,1>(icmp_ln80_reg_274.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_data_V_empty_n.read()));
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_block_state5_pp0_stage0_iter3() {
    ap_block_state5_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_block_state6_pp0_stage0_iter4() {
    ap_block_state6_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_block_state7_pp0_stage0_iter5() {
    ap_block_state7_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_block_state8_pp0_stage0_iter6() {
    ap_block_state8_pp0_stage0_iter6 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_274_pp0_iter5_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, res_V_data_V_full_n.read()));
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln80_fu_123_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_data_V_data_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_274.read(), ap_const_lv1_0))) {
        data_V_data_V_blk_n = data_V_data_V_empty_n.read();
    } else {
        data_V_data_V_blk_n = ap_const_logic_1;
    }
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_data_V_data_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_274.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_V_read = ap_const_logic_1;
    } else {
        data_V_data_V_read = ap_const_logic_0;
    }
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_i_fu_129_p2() {
    i_fu_129_p2 = (!i_0_reg_112.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(i_0_reg_112.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_icmp_ln80_fu_123_p2() {
    icmp_ln80_fu_123_p2 = (!i_0_reg_112.read().is_01() || !ap_const_lv11_400.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_112.read() == ap_const_lv11_400);
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_icmp_ln850_fu_173_p2() {
    icmp_ln850_fu_173_p2 = (!shl_ln_fu_163_p3.read().is_01() || !ap_const_lv26_3FFFFF1.is_01())? sc_lv<1>(): (sc_bigint<26>(shl_ln_fu_163_p3.read()) < sc_bigint<26>(ap_const_lv26_3FFFFF1));
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_icmp_ln851_fu_157_p2() {
    icmp_ln851_fu_157_p2 = (!p_Result_3_i_i_i_fu_149_p3.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_3_i_i_i_fu_149_p3.read() == ap_const_lv10_0);
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_icmp_ln94_fu_232_p2() {
    icmp_ln94_fu_232_p2 = (!tmp_2_fu_222_p4.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_2_fu_222_p4.read() != ap_const_lv3_0);
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_or_ln92_fu_252_p2() {
    or_ln92_fu_252_p2 = (tmp_1_fu_214_p3.read() | icmp_ln94_fu_232_p2.read());
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_p_Result_3_i_i_i_fu_149_p3() {
    p_Result_3_i_i_i_fu_149_p3 = esl_concat<4,6>(trunc_ln851_fu_145_p1.read(), ap_const_lv6_0);
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_res_V_data_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_274_pp0_iter5_reg.read()))) {
        res_V_data_V_blk_n = res_V_data_V_full_n.read();
    } else {
        res_V_data_V_blk_n = ap_const_logic_1;
    }
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_res_V_data_V_din() {
    res_V_data_V_din = esl_zext<16,10>(sigmoid_table1_load_reg_314.read());
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_res_V_data_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_274_pp0_iter5_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_V_write = ap_const_logic_1;
    } else {
        res_V_data_V_write = ap_const_logic_0;
    }
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_select_ln850_fu_192_p3() {
    select_ln850_fu_192_p3 = (!icmp_ln850_fu_173_p2.read()[0].is_01())? sc_lv<13>(): ((icmp_ln850_fu_173_p2.read()[0].to_bool())? select_ln851_fu_185_p3.read(): sext_ln850_fu_170_p1.read());
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_select_ln851_fu_185_p3() {
    select_ln851_fu_185_p3 = (!icmp_ln851_reg_293.read()[0].is_01())? sc_lv<13>(): ((icmp_ln851_reg_293.read()[0].to_bool())? sext_ln850_fu_170_p1.read(): add_ln700_fu_179_p2.read());
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_select_ln92_1_fu_258_p3() {
    select_ln92_1_fu_258_p3 = (!or_ln92_fu_252_p2.read()[0].is_01())? sc_lv<10>(): ((or_ln92_fu_252_p2.read()[0].to_bool())? select_ln92_fu_244_p3.read(): xor_ln91_fu_208_p2.read());
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_select_ln92_fu_244_p3() {
    select_ln92_fu_244_p3 = (!xor_ln92_fu_238_p2.read()[0].is_01())? sc_lv<10>(): ((xor_ln92_fu_238_p2.read()[0].to_bool())? ap_const_lv10_3FF: ap_const_lv10_0);
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_sext_ln850_fu_170_p1() {
    sext_ln850_fu_170_p1 = esl_sext<13,12>(tmp_s_reg_288.read());
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_shl_ln_fu_163_p3() {
    shl_ln_fu_163_p3 = esl_concat<16,10>(tmp_data_0_V_reg_283.read(), ap_const_lv10_0);
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_sigmoid_table1_address0() {
    sigmoid_table1_address0 =  (sc_lv<10>) (zext_ln96_fu_266_p1.read());
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_sigmoid_table1_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()))) {
        sigmoid_table1_ce0 = ap_const_logic_1;
    } else {
        sigmoid_table1_ce0 = ap_const_logic_0;
    }
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_tmp_1_fu_214_p3() {
    tmp_1_fu_214_p3 = add_ln91_fu_203_p2.read().range(12, 12);
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_tmp_2_fu_222_p4() {
    tmp_2_fu_222_p4 = add_ln91_fu_203_p2.read().range(12, 10);
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_trunc_ln851_fu_145_p1() {
    trunc_ln851_fu_145_p1 = data_V_data_V_dout.read().range(4-1, 0);
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_trunc_ln91_fu_200_p1() {
    trunc_ln91_fu_200_p1 = select_ln850_reg_298.read().range(10-1, 0);
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_xor_ln91_fu_208_p2() {
    xor_ln91_fu_208_p2 = (trunc_ln91_fu_200_p1.read() ^ ap_const_lv10_200);
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_xor_ln92_fu_238_p2() {
    xor_ln92_fu_238_p2 = (tmp_1_fu_214_p3.read() ^ ap_const_lv1_1);
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_zext_ln96_fu_266_p1() {
    zext_ln96_fu_266_p1 = esl_zext<64,10>(select_ln92_1_reg_304.read());
}

void sigmoid_array_array_ap_fixed_16_6_5_3_0_1u_sigmoid_config19_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter5.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln80_fu_123_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter5.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln80_fu_123_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

