// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _compute_output_buffer_2d_array_array_ap_fixed_4_2_5_3_0_4u_config2_s_HH_
#define _compute_output_buffer_2d_array_array_ap_fixed_4_2_5_3_0_4u_config2_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0.h"
#include "shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s.h"

namespace ap_rtl {

struct compute_output_buffer_2d_array_array_ap_fixed_4_2_5_3_0_4u_config2_s : public sc_module {
    // Port declarations 21
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<4> > in_elem_data_0_V_read;
    sc_in< sc_lv<4> > in_elem_data_1_V_read;
    sc_in< sc_lv<4> > in_elem_data_2_V_read;
    sc_out< sc_lv<4> > res_stream_V_data_0_V_din;
    sc_in< sc_logic > res_stream_V_data_0_V_full_n;
    sc_out< sc_logic > res_stream_V_data_0_V_write;
    sc_out< sc_lv<4> > res_stream_V_data_1_V_din;
    sc_in< sc_logic > res_stream_V_data_1_V_full_n;
    sc_out< sc_logic > res_stream_V_data_1_V_write;
    sc_out< sc_lv<4> > res_stream_V_data_2_V_din;
    sc_in< sc_logic > res_stream_V_data_2_V_full_n;
    sc_out< sc_logic > res_stream_V_data_2_V_write;
    sc_out< sc_lv<4> > res_stream_V_data_3_V_din;
    sc_in< sc_logic > res_stream_V_data_3_V_full_n;
    sc_out< sc_logic > res_stream_V_data_3_V_write;


    // Module declarations
    compute_output_buffer_2d_array_array_ap_fixed_4_2_5_3_0_4u_config2_s(sc_module_name name);
    SC_HAS_PROCESS(compute_output_buffer_2d_array_array_ap_fixed_4_2_5_3_0_4u_config2_s);

    ~compute_output_buffer_2d_array_array_ap_fixed_4_2_5_3_0_4u_config2_s();

    sc_trace_file* mVcdFile;

    dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0* grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_145;
    shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s* call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176;
    sc_signal< sc_lv<5> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<4> > kernel_data_V_2_3;
    sc_signal< sc_lv<4> > kernel_data_V_2_4;
    sc_signal< sc_lv<4> > kernel_data_V_2_5;
    sc_signal< sc_lv<4> > kernel_data_V_2_6;
    sc_signal< sc_lv<4> > kernel_data_V_2_7;
    sc_signal< sc_lv<4> > kernel_data_V_2_8;
    sc_signal< sc_lv<4> > kernel_data_V_2_12;
    sc_signal< sc_lv<4> > kernel_data_V_2_13;
    sc_signal< sc_lv<4> > kernel_data_V_2_14;
    sc_signal< sc_lv<4> > kernel_data_V_2_15;
    sc_signal< sc_lv<4> > kernel_data_V_2_16;
    sc_signal< sc_lv<4> > kernel_data_V_2_17;
    sc_signal< sc_lv<4> > kernel_data_V_2_21;
    sc_signal< sc_lv<4> > kernel_data_V_2_22;
    sc_signal< sc_lv<4> > kernel_data_V_2_23;
    sc_signal< sc_lv<4> > kernel_data_V_2_24;
    sc_signal< sc_lv<4> > kernel_data_V_2_25;
    sc_signal< sc_lv<4> > kernel_data_V_2_26;
    sc_signal< sc_lv<32> > sX_7;
    sc_signal< sc_lv<32> > sY_7;
    sc_signal< sc_lv<32> > pY_7;
    sc_signal< sc_lv<32> > pX_7;
    sc_signal< sc_logic > res_stream_V_data_0_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > and_ln284_4_reg_868;
    sc_signal< sc_logic > res_stream_V_data_1_V_blk_n;
    sc_signal< sc_logic > res_stream_V_data_2_V_blk_n;
    sc_signal< sc_logic > res_stream_V_data_3_V_blk_n;
    sc_signal< sc_lv<4> > kernel_data_V_2_20_ret_reg_701;
    sc_signal< sc_lv<4> > kernel_data_V_2_19_ret_reg_706;
    sc_signal< sc_lv<4> > kernel_data_V_2_18_ret_reg_711;
    sc_signal< sc_lv<4> > kernel_data_V_2_11_ret_reg_716;
    sc_signal< sc_lv<4> > kernel_data_V_2_10_ret_reg_721;
    sc_signal< sc_lv<4> > kernel_data_V_2_9_ret_reg_726;
    sc_signal< sc_lv<4> > kernel_data_V_2_2_ret_reg_731;
    sc_signal< sc_lv<4> > kernel_data_V_2_1_ret_reg_736;
    sc_signal< sc_lv<4> > kernel_data_V_2_0_ret_reg_741;
    sc_signal< sc_lv<4> > kernel_data_V_2_3_ret_reg_746;
    sc_signal< sc_lv<4> > kernel_data_V_2_4_ret_reg_751;
    sc_signal< sc_lv<4> > kernel_data_V_2_5_ret_reg_756;
    sc_signal< sc_lv<4> > kernel_data_V_2_6_ret_reg_761;
    sc_signal< sc_lv<4> > kernel_data_V_2_7_ret_reg_766;
    sc_signal< sc_lv<4> > kernel_data_V_2_8_ret_reg_771;
    sc_signal< sc_lv<4> > kernel_data_V_2_12_ret_reg_776;
    sc_signal< sc_lv<4> > kernel_data_V_2_13_ret_reg_781;
    sc_signal< sc_lv<4> > kernel_data_V_2_14_ret_reg_786;
    sc_signal< sc_lv<4> > kernel_data_V_2_15_ret_reg_791;
    sc_signal< sc_lv<4> > kernel_data_V_2_16_ret_reg_796;
    sc_signal< sc_lv<4> > kernel_data_V_2_17_ret_reg_801;
    sc_signal< sc_lv<4> > kernel_data_V_2_21_ret_reg_806;
    sc_signal< sc_lv<4> > kernel_data_V_2_22_ret_reg_811;
    sc_signal< sc_lv<4> > kernel_data_V_2_23_ret_reg_816;
    sc_signal< sc_lv<4> > kernel_data_V_2_24_ret_reg_821;
    sc_signal< sc_lv<4> > kernel_data_V_2_25_ret_reg_826;
    sc_signal< sc_lv<4> > kernel_data_V_2_26_ret_reg_831;
    sc_signal< sc_lv<32> > sX_7_load_reg_836;
    sc_signal< sc_lv<1> > icmp_ln284_fu_526_p2;
    sc_signal< sc_lv<1> > icmp_ln284_reg_841;
    sc_signal< sc_lv<32> > sY_7_load_reg_846;
    sc_signal< sc_lv<1> > icmp_ln284_4_fu_536_p2;
    sc_signal< sc_lv<1> > icmp_ln284_4_reg_851;
    sc_signal< sc_lv<32> > pY_7_load_reg_856;
    sc_signal< sc_lv<32> > pX_7_load_reg_862;
    sc_signal< sc_lv<1> > and_ln284_4_fu_594_p2;
    sc_signal< sc_lv<4> > res_out_0_V_reg_872;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_145_ap_ready;
    sc_signal< sc_logic > grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_145_ap_done;
    sc_signal< sc_lv<4> > res_out_1_V_reg_877;
    sc_signal< sc_lv<4> > res_out_2_V_reg_882;
    sc_signal< sc_lv<4> > res_out_3_V_reg_887;
    sc_signal< sc_lv<1> > icmp_ln303_fu_616_p2;
    sc_signal< sc_lv<1> > icmp_ln303_reg_892;
    sc_signal< sc_logic > io_acc_block_signal_op97;
    sc_signal< bool > ap_block_state4;
    sc_signal< sc_lv<32> > select_ln318_fu_637_p3;
    sc_signal< sc_lv<32> > select_ln318_reg_896;
    sc_signal< sc_lv<1> > icmp_ln307_fu_656_p2;
    sc_signal< sc_lv<1> > icmp_ln307_reg_901;
    sc_signal< sc_lv<32> > select_ln313_fu_677_p3;
    sc_signal< sc_lv<32> > select_ln313_reg_905;
    sc_signal< sc_logic > grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_145_ap_start;
    sc_signal< sc_logic > grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_145_ap_idle;
    sc_signal< sc_lv<4> > grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_145_ap_return_0;
    sc_signal< sc_lv<4> > grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_145_ap_return_1;
    sc_signal< sc_lv<4> > grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_145_ap_return_2;
    sc_signal< sc_lv<4> > grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_145_ap_return_3;
    sc_signal< sc_logic > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_start;
    sc_signal< sc_logic > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_done;
    sc_signal< sc_logic > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_idle;
    sc_signal< sc_logic > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_ready;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_0;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_1;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_2;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_3;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_4;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_5;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_6;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_7;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_8;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_9;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_10;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_11;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_12;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_13;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_14;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_15;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_16;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_17;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_18;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_19;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_20;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_21;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_22;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_23;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_24;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_25;
    sc_signal< sc_lv<4> > call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_return_26;
    sc_signal< sc_lv<32> > ap_phi_mux_storemerge_phi_fu_138_p4;
    sc_signal< sc_lv<32> > storemerge_reg_134;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_145_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<32> > add_ln311_fu_661_p2;
    sc_signal< sc_lv<32> > add_ln316_fu_621_p2;
    sc_signal< sc_lv<31> > tmp_fu_546_p4;
    sc_signal< sc_lv<31> > tmp_2_fu_566_p4;
    sc_signal< sc_lv<1> > icmp_ln284_5_fu_556_p2;
    sc_signal< sc_lv<1> > icmp_ln284_6_fu_576_p2;
    sc_signal< sc_lv<1> > and_ln284_3_fu_588_p2;
    sc_signal< sc_lv<1> > and_ln284_fu_582_p2;
    sc_signal< sc_lv<32> > add_ln318_fu_632_p2;
    sc_signal< sc_lv<32> > add_ln313_fu_672_p2;
    sc_signal< sc_lv<5> > ap_NS_fsm;
    sc_signal< bool > ap_condition_175;
    sc_signal< bool > ap_condition_184;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<5> ap_ST_fsm_state1;
    static const sc_lv<5> ap_ST_fsm_state2;
    static const sc_lv<5> ap_ST_fsm_state3;
    static const sc_lv<5> ap_ST_fsm_state4;
    static const sc_lv<5> ap_ST_fsm_state5;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<31> ap_const_lv31_0;
    static const sc_lv<32> ap_const_lv32_41;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln311_fu_661_p2();
    void thread_add_ln313_fu_672_p2();
    void thread_add_ln316_fu_621_p2();
    void thread_add_ln318_fu_632_p2();
    void thread_and_ln284_3_fu_588_p2();
    void thread_and_ln284_4_fu_594_p2();
    void thread_and_ln284_fu_582_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_block_state4();
    void thread_ap_condition_175();
    void thread_ap_condition_184();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_storemerge_phi_fu_138_p4();
    void thread_ap_ready();
    void thread_call_ret_shift_line_buffer_array_ap_fixed_4_2_5_3_0_3u_config2_s_fu_176_ap_start();
    void thread_grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_config2_mult_0_0_0_0_0_fu_145_ap_start();
    void thread_icmp_ln284_4_fu_536_p2();
    void thread_icmp_ln284_5_fu_556_p2();
    void thread_icmp_ln284_6_fu_576_p2();
    void thread_icmp_ln284_fu_526_p2();
    void thread_icmp_ln303_fu_616_p2();
    void thread_icmp_ln307_fu_656_p2();
    void thread_io_acc_block_signal_op97();
    void thread_res_stream_V_data_0_V_blk_n();
    void thread_res_stream_V_data_0_V_din();
    void thread_res_stream_V_data_0_V_write();
    void thread_res_stream_V_data_1_V_blk_n();
    void thread_res_stream_V_data_1_V_din();
    void thread_res_stream_V_data_1_V_write();
    void thread_res_stream_V_data_2_V_blk_n();
    void thread_res_stream_V_data_2_V_din();
    void thread_res_stream_V_data_2_V_write();
    void thread_res_stream_V_data_3_V_blk_n();
    void thread_res_stream_V_data_3_V_din();
    void thread_res_stream_V_data_3_V_write();
    void thread_select_ln313_fu_677_p3();
    void thread_select_ln318_fu_637_p3();
    void thread_tmp_2_fu_566_p4();
    void thread_tmp_fu_546_p4();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
